### ISSUE TITLE
option for immutable model?

### ISSUE THREAD

**Issue by dave-doty** [seed-rs/seed#167]
Is there a way to have an immutable Model as in Elm? The examples I've found don't return anything from `update` and mutate the model in place, e.g., https://github.com/David-OConnor/seed/blob/master/examples/counter/src/lib.rs#L37

The type signature of `update` suggests this is not possible, since it takes `&mut Model` as a parameter, and doesn't seem to have a return value: https://github.com/David-OConnor/seed/blob/master/src/vdom.rs#L141

**Comment by David-OConnor** [comment]
It was originally set up this way. Made a breaking switch to the current style, since it (subjectively) makes the API easier to work with, and works well with Rust's mutable-reference pattern.

Check out [Sapir's PR that introduced this](https://github.com/David-OConnor/seed/pull/69) - his reasoning should be what you're looking for.

**Comment by MartinKavik** [comment]
It's not possible, why do you need it? Do you have an example where this API is problem?

**Comment by MartinKavik** [comment]
From my experience it's a little bit annoying when you want to represent model as enum and switch among its variants in update function.

**Comment by dave-doty** [comment]
I haven't learned Rust yet, so I don't know what Rust's mutable-reference pattern is. Is there a page somewhere describing it?

The option for immutability (alongside efficient immutable data structures) helps, for example, to make a dead-simple Undo-Redo mechanism. You just keep a stack of all Models, and Undo amounts to simply popping Models off the Undo stack and pushing them on the Redo stack.

I read through the PR David linked, and (though I'm not yet versed enough in Rust to understand the whole thing) it seems the high-level summary is that the old way allowed the option of mutating in-place or returning a new Model, but that for one update function signature to handle both options, mutating in-place required more tedious boilerplate to be able to return a reference to the mutated model, due to Rust's borrow checking.

I wonder if another way of handling this, which doesn't require the user to return a Model (or reference to a Model) when mutating in-place is to have `update` (in addition to whatever else it returns) to return an `Option<Model>`, where Seed assumes the Model was mutated in-place if `None` is returned, but uses `model` if the return value is `Some(model)`.

**Comment by David-OConnor** [comment]
An example update function from an earlier version, which I think is inline with what you're suggesting:
```rust
fn update(msg: Msg, model: Model) -> Model {
    match msg {
        Msg::Increment => Model {count: model.count + 1, ..model},
        Msg::Decrement => Model {count: model.count - 1, ..model},
        Msg::ChangeWWC(what_we_count) => Model {what_we_count, ..model },
    }
}
```

**Comment by David-OConnor** [comment]
I'm open to adding this [back] if we can do it in a way that still allows `&mut` updating.

**Comment by MartinKavik** [comment]
I've created some examples in Seed's branch [demo/immutable](https://github.com/MartinKavik/seed/tree/demo/immutable) so we can discuss concrete use cases.

- `examples/immutable` (run with `cargo make start immutable`) - it demonstrates how to wrap up `Model` into `Option` so we can owned it in `update` function.
- `examples/immutable_2` - a simple undo/redo implementation.
- `examples/immutable_3` - how to switch between pages with shared data, where `Model` is `enum` and pages are its variants (simple state machine).

I don't think of example where `&mut Model` would be problem.

**Comment by spersson** [comment]
I agree with Martin here, can't think of a reason to start copying a model instead of mutating it in place. Undo/redo on a user level can be done like in martins second example. Undo/redo for a debug version of a seed app (like what elm can do) could be done by seed cloning the model before calling update().
My understanding of why functional languages do this immutability is to avoid a mutation to unexpectedly affect another corner of your app. Rust solves this by not allowing you to have references in these troublesome ways.

**Comment by David-OConnor** [comment]
> My understanding of why functional languages do this immutability is to avoid a mutation to unexpectedly affect another corner of your app. Rust solves this by not allowing you to have references in these troublesome ways.

This is an important point: This reason why immutable patterns are encouraged in some languages doesn't apply in Rust.

**Comment by dave-doty** [comment]
Hi Martin: Isn't the undo/redo implementation going to be inefficient with a large model? If you are using efficient immutable data structures, then no matter the size of the model, keeping a stack of all models since the program started is cheap. However, if you are cloning the model on each update, then the cost is much higher, it's size_of_model*number_of_updates.

It's not impossible to do undo/redo with a mutable model, but I think it requires being careful to define an inverse operation for every Msg and then maintaining a stack of Msg's, if you don't want the expensive cost of having a copy of every Model that has existed since the program booted.

**Comment by MartinKavik** [comment]
> Isn't the undo/redo implementation going to be inefficient with a large model?

Yeah, it was a simple example to demostrate that is possible in Seed to _"popping Models off the Undo stack and pushing them on the Redo stack"_, because I like the rule _"Premature optimization is the root of all evil"_. If I want to be efficient I would probably look at something like https://docs.rs/im/13.0.0/im/ (read its super documentation), or https://docs.rs/rpds/0.6.0/rpds/.

But as usual it depends on your use case - what data you want to store, how long, etc. If you want to write complex things, something like https://github.com/xi-editor/xi-editor (see description of its [`undo`](https://github.com/xi-editor/xi-editor/blob/master/docs/docs/crdt.md#undo)), it's possible that Rust and its mutability can be advantage because of efficiency of operations on mutable storage.

**Comment by jesskfullwood** [comment]
I prefer the immutable model, but I will admit it doesn't work so great with Rust, because RefCell and friends mean you can't guarantee nothing has changed even if `fn update` provided an immutable `&Model` rather than `&mut Model`.

Nevertheless, the way `update` works, relying entirely on in-place mutation, doesn't sit right with me. Particularly the `Orders` object seems like a strange choice - what was the problem with returning a `Cmd<Msg>` like Elm? I toyed around with a Seed-like library and found that this API [worked very nicely](https://github.com/jesskfullwood/fig/blob/master/examples/demo/src/lib.rs#L76).

Another thing Elm did right was to completely hide the `App` type from the user. Instead it just has a top-level `application` function which sets things in motion.

I like this library a lot, but the things I dislike are generally where it strays from Elm's very elegant design.

**Comment by David-OConnor** [comment]
The `App` being exposed is an implementation detail, not a design choice - I agree that it's inelegant, but haven't found a way around it. Might re-attack this.

**Comment by jesskfullwood** [comment]
Good to hear, I think it is worth doing. You could stash it in a thread-local. You need to type-erase it first, just box it and store as a void pointer. It's all super-unsafe, but it [works](https://github.com/jesskfullwood/fig/blob/master/src/lib.rs#L190)

**Comment by stephanbuys** [comment]
As someone who's experimenting with seed and ramping up to build something relatively big in a rust front-end framework (most probably seed) I would love to understand the reasoning here.

I've been a rust developer for almost 4 years now and one of the things I appreciate about the language is that you can reason about the code and tell what it's doing, sometimes this results in verbose code (as compared to other languages) but a little more code and clarity gets my vote over having to hide aspects of the code and using unsafe tricks to do so (potentially introducing issues?)

All that said I'm not suggesting that @jesskfullwood's suggestions are bad but I would love to hear what is gained by this approach apart from imitating elm? (This sounds harsher that its meant)

One of the immediate things I appreciated about seed vs yew (which I evaluated extensively about 8 months ago) was its clarity, its reliance on crates that also were very easy to reason about (js-sys and web-sys) as well as it not relying on scaffolding like cargo-web, but clearly showing exactly how it works and is invoked. 

If it means anything at all to the developers I would advocate for not using tricks or imitating other languages at the costs of losing some rust idioms. That said, I've never used elm so I might be missing something.

**Comment by jesskfullwood** [comment]
I am not very happy with my above comments, I should have explained myself properly - so here goes.

I am in the middle of writing a large frontend project in Rust. I started with seed a few months ago, then moved towards my own framework (linked above) mainly for the purposes of experimentation. I am now at the point where I don't want to maintain a framework as a one-person-show and would like to move back to seed and start contributing.

My view is that our overall objective is to seriously limit the surface area where 'things can happen'. Anyone who has tried to make a web app by Just Coding in Javascript knows how quicky it becomes and unmanageable mess of callbacks and implicit state and behaviour. The elegance of Elm comes from the fact that at any moment in time, the entire state of the app is contained in the Model and the only way way to modify the model is to send messages to the `update` function. All the business logic is contained somewhere within `update`. (I'm sure everyone using `seed` already appreciates this.)

The conceptual model I have for the update loop is a command comes from 'somewhere' (a DOM event, a `fetch`, a URL change) and kicks off an update, which updates the model and may kick off more commands, which are repeatedly applied to the model until no more commands are generated. Then we render the DOM and wait for another command. This keeps our view stage completely declarative and cleanly separates it from our business logic. Let us call this the FRP model (who knows what FRP really is).

```
receive command ------> update model -----> render
  |                        | 
   <----- more commands --<
```

Now I am not particularly interested in precisely copying Elm, but I am very interested in severely constraining 'when and where things happen', and Elm does a lot right in this regard. It is however let down by a weak type system (no traits/typeclasses) so I am sure that Rust can improve on it in many places (Elm is also rather verbose IMO).

So, about Seed. For the most part it adheres to FRP logic and all model updates do indeed happen in the `update` function, but IMO the main flaw is that it does not cleanly separate out the stages of the update loop. Some examples I found while poking around, these may be others:

Firstly, it is possible to get hold of the App and run `app.update(msg)` at arbitrary points. For example this method could be run inside an `onClick` callback, subverting our event loop.

Secondly the lifecycle hooks (`did_mount` etc) allow the rendering phase to directly generate messages. This means the view is not purely declarative, and also exposes what I consider to be implementation details (the app should not care exactly when or how an element is created or destroyed).

Thirdly, the signature of the `update` function.
```
fn update(msg: Msg, model: &mut Model, _: &mut Orders<Msg>);
```
As I mentioned above, I'm not a huge fan of having `&mut Model` and would be happier if it just provided an owned `Model` and received it back in the return type, however Rust mutability is not as dangerous as other langugages and it does have some ergonomic advantages.

On the other hand the `&mut Orders` seem to break functional idioms for no reason, and I think just returning `Cmd<Msg> or better `(Model, Cmd<Msg>)` would be preferable. A particular problem with `Orders` is that it allows control of the rendering cycle which again subverts the update loop. It is not up to the user to decide when and how things get rendered. Once control is relinquished from the update loop, view should simply reflect the app state, i.e. the Model.

So, obviously I would be in favour of a refactor to adhere more closely to the FRP idiom, but equally, this is not my project and other people have other ideas, I just wanted to kick off a discussion. I would love this library to be the new Correct Way to write web apps!

A quick note on `unsafe` - I don't like using it but if it is used in a controlled way it need not (indeed must not) leak into the user-facing API. In this instance I found it to be necessary to present the API I outlined above, but YMMV.

**Comment by stephanbuys** [comment]
@jesskfullwood this is an awesome clarification, thank you, lots of sensible reasoning to digest here. My initial reaction was based on structural imitation but I can tell you're advocating for carefully (and predictably) managing the state and the DOM.

**Comment by MartinKavik** [comment]
The last comment is several months old and I don't see any specific problems to resolve so I suggest to close it. 
If you have some ideas how to make Seed better, please create a proposal, ideally, with a real-world problem example.

**Comment by MartinKavik** [comment]
Closing. Please use Seed's forum for similar questions.
