### ISSUE TITLE
HTML to seed convertor

### ISSUE THREAD

**Issue by TatriX** [seed-rs/seed#175]
It would be nice to have a tool which can convert html to seeds code.
So before digging and implementing one I first want to check that there are no such thing yet.

My plan is to make a library, which then can be used in cli tool as well as in wasm so it can be used in a simple web based converter.

**Comment by stephanbuys** [comment]
I was thinking something similar and had a loot at https://github.com/bodil/typed-html as a possible framework to do this with. The typed-html crate specifically supports emitting a walkable output. Only problem was that it required strings to be quoted, so that doesn't really solve your problem.
Also had a look at seed's ability to do "raw" elements (from string), which I ultimately concluded would work ok for things like layouts, etc.

**Comment by David-OConnor** [comment]
I think the best approach would be to create a string of macros from a seed vdom tree, since we can create that tree use `El::from_html.

**Comment by TatriX** [comment]
Probably I wasn't clear enough.
What I want is essentially a web page with a textarea to which I can copy html code and to get a generated code to paste into my source files.
So paste `<div>hi!</div>` and get `div!["hi"]` back.

**Comment by MartinKavik** [comment]
Something like https://mbylstra.github.io/html-to-elm/?

**Comment by TatriX** [comment]
Yep, looks, good!

**Comment by TatriX** [comment]
Here's some progress. I used `html5ever` and `rustfmt` for parsing and formatting respectively.
This means you can configure output format with `rustfmt.toml`. 
![2019-07-04-153701_2769x1019_scrot](https://user-images.githubusercontent.com/703150/60670710-9cc28e80-9e71-11e9-83f4-cdf5e0fe0821.png)

**Comment by TatriX** [comment]
And here is a web version (very raw) https://tatrix.org/public/html-to-seed/

**Comment by MartinKavik** [comment]
@TatriX Please create PR to https://github.com/MartinKavik/awesome-seed-rs once it's at least beta version. I suggest to close the issue.

**Comment by TatriX** [comment]
Sure, sounds good!

**Comment by stephanbuys** [comment]
This would be a great addition to `examples/` or something equivalent, or even a part of the seed website.

**Comment by David-OConnor** [comment]
Agree on posting to `awesome-seed-rs`, and the website. I'm not sure how it would fit as an example, since it's a tool.

**Comment by stephanbuys** [comment]
Perhaps just the website then, it's just very handy when you have snippets to convert to the macro format. But its just an idea.
