### ISSUE TITLE
Ask: seed::fetch::FailReason not fit Serialized

### ISSUE THREAD

**Issue by daogangtang** [seed-rs/seed#225]
When I use seed::update(Msg), and if a variant of Msg contains fetch::ResponseDataResult<_>, compiler will complain the following:
```
...
::_IMPL_DESERIALIZE_FOR_Token::_serde::Serialize` is not satisfied
```

I want to ask whether this type be implemented Serialized? 

Thank you.

**Comment by MartinKavik** [comment]
Can you use `clone_app()` + `msg_mapper()` instead of `seed::update`? 
See `2. change` in https://github.com/David-OConnor/seed/pull/189 for more info. Example here: https://github.com/David-OConnor/seed/blob/master/examples/animation_frame/src/lib.rs#L72.

**Comment by daogangtang** [comment]
Thank you very much, but no, I can't access `app/orders` in my context (which is in view function).

**Comment by MartinKavik** [comment]
@daogangtang Why do you need it in `view`? Could you provide some context? (link to repository, a part of code, similar example..)

**Comment by daogangtang** [comment]
Hi,  the context is:
```
pub fn view(model: &Model) -> Node<Msg> {
         // use this empty div to act as a event placeholder
         div![
             did_mount(move |_| {
                 seed::update(Msg::PageLoaded);
             })
         ]
    ]
}
```

I use it in did_mount in an element, as the hook of lifecycle when page loaded.

**Comment by MartinKavik** [comment]
I don't recommend to use hooks (see https://github.com/David-OConnor/seed/issues/200#issuecomment-521961446).
Why do you need to know when the page is loaded? (I want to help you zoom-out and find a better solution / architecture).

**Comment by daogangtang** [comment]
Thank you, cause that I want to make a https request to load some data when that page loaed, and that page is child page  (not in the lib.rs).

**Comment by MartinKavik** [comment]
I see you liked [seed-rs-realworld](https://github.com/MartinKavik/seed-rs-realworld) and your description sounds exactly like the pattern used in this project:

> request to load some data when that page loaed

-> e.g.: https://github.com/MartinKavik/seed-rs-realworld/blob/master/src/page/settings.rs#L63

If architecture in RealWorld example doesn't make sense on the first look, try to look at https://github.com/David-OConnor/seed/blob/master/examples/server_integration/client/src/lib.rs - it's the same pattern in its "pure form" (no routing and all "child pages" are on the same page at once, but it's not important).

**Comment by daogangtang** [comment]
Yes, very appreciated that! I'll look at your design pattern on it.

Very valuable information. Thank you.

**Comment by MartinKavik** [comment]
@daogangtang was it useful? Can we close the issue?

**Comment by MartinKavik** [comment]
2 months without the answer, closing,
