### ISSUE TITLE
Movement towards async/await

### ISSUE THREAD

**Issue by AlterionX** [seed-rs/seed#284]
If I understand correctly, we're using futures 0.1, meaning that it's a bit annoying to work with since async/await is landing in stable. It would chafe a little bit to have to convert between the two.

So the natural question is: how hard/complicated would it be to move to using async/await and `std::future` + friends instead of futures 0.1?

An extension of this is found in #226.

**Comment by MartinKavik** [comment]
Anothe related issue: https://github.com/David-OConnor/seed/issues/131

**Comment by zimond** [comment]
I'll try this one

**Comment by zimond** [comment]
here it is: #307 307

**Comment by AlterionX** [comment]
I believe this was closed? I'm going to close this.
