### ISSUE TITLE
Recommended way to unit test returned html macro contents?

### ISSUE THREAD

**Issue by craigmayhew** [seed-rs/seed#294]
Hello,

What is an appropriate way to unit test nested element macros?

e.g. if I have a function like so and I want to write a unit test for checking it returns some or all of the expected content:

```rust
fn draw_title(){
  div![h1!["some string"]]
}
```

**Comment by David-OConnor** [comment]
I don't have a good answer at the moment. Two approaches that come to mind depending on your intent are to compare the macro's output to the 1) Vdom code (ie `Node`, `El` etc), or 2) To `web_sys` code (ie `web_sys::Node`, `web_sys::Element` etc). From a preliminary look, I don't think we expose enough functions to do this. Ie `seed::make_websys_el` could be used for case 2, but is private.

**Comment by craigmayhew** [comment]
In this FAQ page/file for instance, I would like to test the returned content contains a well formatted link to github: https://github.com/craigmayhew/bigprimes.net/blob/master/src/pages/faq.rs

This would allow me more confidence in my tests when upgrading seed-rs as a dependency.

I also intend to test this in functional testing with a web browser, but it's far quicker to get feedback from unit tests for an initial pass.

**Comment by David-OConnor** [comment]
I'm working on adding a helper function that will return a `Node`'s  rendered HTML.

**Comment by MartinKavik** [comment]
@David-OConnor Is it still in your todo list?

**Comment by MartinKavik** [comment]
See https://github.com/seed-rs/seed/blob/master/examples/tests/src/lib.rs#L87-L112

**Comment by aklajnert** [comment]
Hi @MartinKavik, [this page](https://seed-rs.org/0.8.0/todomvc_refactor) from the tutorial links to this issue. Since it's closed, shouldn't the link be removed/updated?

**Comment by MartinKavik** [comment]
Hi @aklajnert and thanks for the feedback! 
You are right, feel free to update the text how you think it would make sense. Perhaps the link above with a test would be useful. 
I will be glad. Thank you.
