### ISSUE TITLE
controlled/uncontrolled for input

### ISSUE THREAD

**Issue by hwchen** [seed-rs/seed#295]
I'm a little confused by this paragraph from the guide:

```
Input elements are controlled

input, textarea, and select elements are always controlled, in the vein of React. This means that even if there’s no event associated with user input to these fields, their value will always stay in sync with the model, which may mean ignoring text input if not set up with a Ev::Input event.
```
- I'm not that familiar with frontend, but it looks like react can have both controlled and uncontrolled input? https://medium.com/@AndrewBonner2/controlled-components-in-react-920f3e795d87
- In my own app, I was able to omit having `value` refer to state, and it works fine (this should be uncontrolled?). And in the examples like todomvc, I see what looks like controlled inputs.

So, hoping that you can clarify a bit on what the guide means.

**Comment by David-OConnor** [comment]
The intent was to force all `input`/`textarea`/`select` to be controlled, unlike React, which lets you do either. Ie force the input to be in sync with the model. We never completely worked this out, ie there were some edge cases (I can't remember which) that could exhibit uncontrolled/desynced behavior if you left out `value`. Could you please post a code snippet of the code that triggered the uncontrolled behavior? It may be worth completing this, or assessing if we want to allow uncontrolled behavior.

I'm adjusting the guide paragraph to clarify that we're referring only to React's controlled behavior.

**Comment by hwchen** [comment]
https://github.com/hwchen/frontend-counter-test-rs/blob/master/seed-test/src/lib.rs#L68

I believe I'm using this input in an uncontrolled manner. But let me know if I'm not and I misunderstood :)

**Comment by David-OConnor** [comment]
Appreciate it - You didn't misunderstand anything; that behavior wasn't [i]supposed[/i] to be allowed, but the code supposed to prevent it isn't working right.

**Comment by MartinKavik** [comment]
@David-OConnor 
> the logic intended to prevent it is broken

Could you point me to the implementation (link to code)?

---

`controlled component` is a new term for me - but if I understand correctly, you basically want to "move" web component's (element's) state (model) into app's state (model). And you do this by binding element's properites (e.g. `value`) with `Model` and handling associated change events (e.g. `InputEvent`).

I can imagine doing this for simple elements like `input` and `textarea` but for more complex elements and custom ones it would be pain imho. 
And how you determine which variables you want to "move" into App state? Is `value` enough or you need to "move" also other vars like `max_length`, `mask`, `type`, etc..?

So..
 - What problems should preventing `uncontrolled components` solve?
 - How we define `uncontrolled/controlled components`?

**Comment by MartinKavik** [comment]
UPDATE:
Internal input listeners have been removed in PR https://github.com/seed-rs/seed/pull/330. So input elements are not controlled anymore and you shouldn't modify their value directly.

@David-OConnor Could you update / remove that paragraph in the guide? (https://seed-rs.org/guide/misc-features).

@hwchen Do you have some questions? Or can we close it?

**Comment by hwchen** [comment]
No questions here, thanks! Looks like a lot of new changes to seed so I might poke around a bit.
