### ISSUE TITLE
Readme.md - community feedback

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#302]
Hi!
We want to make Seed's documentation as good as possible. 
Could you help us to make `Readme.md` better?

- Do you think that something is missing?
- Are code examples good enough? (too simple? too complex? too few comments?, ..)
- Is it beginner-friendly?
- Are there any unnecessary sections?
- Did you find a typo?
- Are any parts hard to read or understand?
- Are any parts ugly / not formatted or not styled enough?
- Did you find out-of-date info or dead links?
- etc.

Thank you!

**Comment by MartinKavik** [comment]
@hwchen's feedback (https://github.com/seed-rs/seed/issues/111#issuecomment-557940501):
I'm a backend dev exploring Rust front-end frameworks. Of course, one of the first things I tried to do was make a component :). But reading through this issue, and reading some of the Elm discussion links helped me understand the theory of this framework.

It would have be helpful to me if this "reusable views over nested components" was mentioned explicitly in the Readme. I think it's easy to understand the basic Elm architecture pretty easily, but understanding preferred patterns for more complex apps is not obvious. As it is, I had to search several issues for the answer.

**Comment by nielsle** [comment]
The readme is great. Here is a small nitpick. The "short example" does not tell the user to create a `Makefile.toml` and  terefore  `cargo make serve` did not work for me
~~~
[cargo-make] INFO - cargo make 0.26.2
[cargo-make] INFO - External file not found or is not a file, skipping.
[cargo-make] INFO - Project: test
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: serve
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task not found: serve
[cargo-make] WARN - Build Failed.
~~~

**Comment by MartinKavik** [comment]
@nielsle Thanks!
@David-OConnor Could you fix it once you have some time?
