### ISSUE TITLE
Website & Readme.md - community feedback

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#303]
Hi!
We want to make Seed's website and documentation as good as possible.

If you want to help a little bit, please see those issues for more info:
- Feedback for **Website** - https://github.com/seed-rs/seed-rs.org/issues/3
- Feedback for **Readme.md** - https://github.com/seed-rs/seed/issues/302

Thank you!

**Comment by daxpedda** [comment]
The docs on `docs.rs` aren't building for `0.5.0`.

**Comment by tiberiusferreira** [comment]
The website is really good! Thanks! 
The only small problem is that if you switch to dark mode and refresh the page, it first renders in light mode, then switches.

**Comment by rebo** [comment]
The new websites great, I really think because Seed is big enough and active enough that it should have an online chat presence, i.e. a Discord or something.

**Comment by flosse** [comment]
The new website is showing an outdated version (`0.4.2 (Nov 05, 2019)`) but the overall documentation is quite good :)

One thing that might be interesting for companies would be a section **Commercial Support** so that people can see that seed is more than just a hobby project.

**Comment by MartinKavik** [comment]
> an online chat presence, i.e. a Discord or something

I was thinking about it, but I (we?) don't have capacity to take care of it (chat, forum, twitter, etc.) in the near future. However if you (@rebo) or anybody else want to help with it, just write us a mail :)

**Comment by MartinKavik** [comment]
> The new website is showing an outdated version (0.4.2 (Nov 05, 2019))

Yeah, `seed-rs.org` content for `Seed 0.5.0` is WIP ([PR](https://github.com/seed-rs/seed-rs.org/pull/2)). We also have to redeploy docs (? @David-OConnor) to fix official Rust docs. 

They are process errors, we should update docs and `seed-rs.org` content before the Seed release.

**Comment by MartinKavik** [comment]
> a section Commercial Support

@flosse Could you create an issue in https://github.com/seed-rs/seed-rs.org and describe a little bit what you think that should be in this section from your point of view?

**Comment by flosse** [comment]
> @flosse Could you create an issue in https://github.com/seed-rs/seed-rs.org and describe a little bit what you think that should be in this section from your point of view?

see https://github.com/seed-rs/seed-rs.org/pull/9

**Comment by MuhannadAlrusayni** [comment]
Great job :+1: , the website is far better than the old one.

**Comment by TatriX** [comment]
I created [Discord channel](https://discord.gg/NQPmVR). Feel free to join!

**Comment by David-OConnor** [comment]
I'm getting `invalid invite`.

**Comment by TatriX** [comment]
It turns our that invite links has expire date.
Here's unlimited one: https://discord.gg/JHHcHp5

**Comment by anderejd** [comment]
I have only skimmed the new website, but it looks great! Bonus points for the dark mode button <3

**Comment by decafbad** [comment]
About update function:
" It accepts a message and a model as parameters, and returns an Update struct. Update contains ShouldRender and Effect enums."
It doesn't return anything. This paragraph is either outdated or ambiguous.

**Comment by MartinKavik** [comment]
@decafbad Thanks for feedback! We plan to rewrite guides after Seed 0.7.0 release (released in next weeks). I'll try to update also docs for 0.6.0.

**Comment by flosse** [comment]
> Seed 0.7.0 release (released in next weeks).

:tada: awesome!

**Comment by decafbad** [comment]
at https://seed-rs.org/0.7.0/use/ I removed #![allow(clippy::wildcard_imports)] but no clippy errors.

**Comment by MartinKavik** [comment]
@decafbad Try to change something in the Rust code, save it and then run `cargo make clippy`. There is a bug in `clippy` - it sometimes doesn't lint the code at all if it's already compiled.

**Comment by decafbad** [comment]
It works fine now, after I ran a **second** `cargo clean`. Couldn't get what's wrong.
