### ISSUE TITLE
Seed 0.5.0 todos

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#308]
- [x] fix docs
- [ ] maybe update release checklist - _"update `seed-rs.org` before the release"_

**Comment by MartinKavik** [comment]
https://github.com/seed-rs/seed/pull/306

**Comment by David-OConnor** [comment]
I think pt 2 is covered under `Ensure both the readme and homepage website reflect API changes. Instructions for updating the homepage are available here`.

**Comment by MartinKavik** [comment]
@David-OConnor Can you look at it once you have time please so we can close it?

**Comment by MartinKavik** [comment]
@David-OConnor I assume you'll release version 0.6.0 soon and update release checklist how it make sense to you. 
Closing.
