### ISSUE TITLE
listeners disapper when cloneing Node or El

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [seed-rs/seed#316]
I'm trying to store nodes in structs and use them later in view.

use case:
``` rust
    #[derive(Clone, Debug)]
    pub enum Msg {
        Home,
        AboutUs
    }

    #[derive(Debug)]
    pub struct Flexbox {
        items: Vec<Node<Msg>>,
    }

    fn view_flexbox(flexbox: &Flexbox) -> Node<Msg> {
        div![
            flexbox.items.clone()
        ]
    }

    #[test]
    fn test_listeners() {
        let items = vec![
            button![simple_ev(Ev::Click, Msg::Home), "Home"],
            button![simple_ev(Ev::Click, Msg::AboutUs), "About us"]
        ];

        let flexbox = Flexbox {items};
        // this panic show that flexbox items have listeners
        panic!("{:#?}", flexbox);
        let node = view_flexbox(&flexbox);
        // this panic show that node doesn't children doesn't have listeners
        panic!("{:#?}", node);
    }

```

It seems listeners are not cloned with the node/el:

https://github.com/seed-rs/seed/blob/60d7de4386b18e95091d5f16716664f77cfed003/src/virtual_dom/node/el.rs#L206-L221

Is there way to fix this ?

**Comment by MartinKavik** [comment]
I don't know, @David-OConnor ?
However I've added it to my todo-list - https://github.com/seed-rs/seed/issues/293. I plan to do a bigger update for virtual DOM in January.
Or you can try to fix it.

**Comment by MuhannadAlrusayni** [comment]
I don't think I can do it, and if I try I need to understand the internal code for seed first and this would need non trivial time which I don't have right now.

**Comment by MuhannadAlrusayni** [comment]
Yew seems to have similar issue, and they already have draft PR https://github.com/yewstack/yew/pull/786 , it might be helpful to get some inspiration from them.

**Comment by MartinKavik** [comment]
@MuhannadAlrusayni thanks. I'll be working on it in January.
Closing in favor of #293

**Comment by MuhannadAlrusayni** [comment]
I got time to solve this issue, but I need some assistance :D.

So the problem is that `Listener<Ms>` doesn't implement `Clone`, it also contains `EventHandler<Ms>` and `Closure<_>` both don't implement `Clone` too.

First let's talk about `EventHandler<Ms>` which contains a closure `Box<dyn FnMut(web_sys::Event) -> Ms>`, this closure will be used to create `Closure<_>` in `attach` function.
 
Then we have `Closure<_>` which get created in `attach` function, and passed to `add_event_listener_with_callback` which add event listener in js world, `Listener<Ms>` stores this closure so it can detach it later with `detach` function.

If I understood correctly, `EventHandler<Ms>` must be cloned when we clone `Listener<Ms>`, while `Closure<_>` shouldn't be cloned when we clone `Listener<Ms>`.

So we have to implement `Clone` for `EventHandler<Ms>`, one way to do that is by wrap type that contain `Rc`. Then implement `Clone` for `Listener<Ms>`.

Please correct me if I miss something, if I my understood is correct I can open PR for this.

**Comment by MuhannadAlrusayni** [comment]
cc @MartinKavik @David-OConnor ?

**Comment by MartinKavik** [comment]
@MuhannadAlrusayni sorry for the delay. I've written some comments to PR, but I don't know that code so well to answer you properly.
And see my todos with VirtualDOM - https://github.com/seed-rs/seed/issues/293 (especially point 1.) - Listener patching has to be refactored to fix some issues and improve performance. I hope I can remove `Ms: Clone` restrictions as a side-effect.
