### ISSUE TITLE
Setup a benchmark

### ISSUE THREAD

**Issue by kaushalyap** [seed-rs/seed#324]
Setup a benchmark with [other WASM front end frameworks](https://github.com/flosse/rust-web-framework-comparison#frontend-frameworks-wasm) like Yew, Percy

Also add Seed to [this benchmark ](https://github.com/krausest/js-framework-benchmark) which will allow us to compare Seed with front-end JS frameworks/libraries, currently Yew is there.

**Point of benchmarking**

- Way to compare with other frameworks/libraries
- To identify places where we could improve performance
- To know about performance regressions

**Comment by kaushalyap** [comment]
I suggest you to compare Yew with other JS frameworks using [this benchmark](https://krausest.github.io/js-framework-benchmark/current.html), I think seed will be able to do better than Yew or may be better than JS frameworks/libraries, since as I read the following in [here](https://www.reddit.com/r/rust/comments/a7h53y/considering_rust_for_frontend/ec31hru?utm_source=share&utm_medium=web2x)  

> Yew is based on stdweb that has a lot of features but also is really heavy-weight. Frameworks like seed on the other hand are based on wasm-bindgen that is focused on (mostly) "zero-cost" interaction with e.g. the. DOM etc.

**Comment by MartinKavik** [comment]
@seed-rs/core, @kaushalyap Is there a volunteer?

I have VirtualDOM updates in my todo list so it would be nice to compare results before and after refactor. And comparing with other frameworks would be very nice for marketing (or motivation to make it better 😃 ).

**Comment by kaushalyap** [comment]
@MartinKavik sorry to say currently I do not have enough free time. Hopes someone will do it.

**Comment by MartinKavik** [comment]
https://github.com/krausest/js-framework-benchmark/pull/696

**Comment by MartinKavik** [comment]
- Support for element keys has been merged (https://github.com/seed-rs/seed/pull/357), so we should add keyed version to [krausest/js-framework-benchmark](https://github.com/krausest/js-framework-benchmark).

- @1init found this benchmark - https://github.com/ivanceras/sauron-perf. I think it's good enough to write about it in README.

- There is a new example - [bunnies](https://github.com/seed-rs/seed/tree/master/examples/bunnies) - it can be a good demonstration of performance for browser games.

_Note_: Benchmark updates should be done once Seed 0.7.0 is released.

**Comment by Ben-PH** [comment]
Now that benchmarks are up, it would be good to update the about section on the webpage.

[ctrl-f performance](https://seed-rs.org/) for the relevant part.

It might also be worth having a section on performance. Speaking from my own perspective, I'm coming from a very "low-level and systems" background and have little grasp of frontend considerations. An overview that puts the performance traits of seed into context would be quite useful for me.

**Comment by MartinKavik** [comment]
@Ben-PH Thanks for feedback/ideas.

I want to rewrite the content of seed-rs.org after the next release, so I'll try to add a section on performance and I'll maybe add it also into the README.

We've decided to not include it in README yet, because the main focus is still on the best public API as possible, so we don't have many benchmarks and Seed isn't very optimized yet (but the speed should be enough for the most use-cases now).

However there is a growing list of possible improvements - https://github.com/seed-rs/seed/issues/385 (see also comments and don't be afraid to recommend new ideas) and it's on our [roadmap](https://github.com/seed-rs/seed/milestones).

**Comment by Ben-PH** [comment]
>  because the main focus is still on the best public API as possible.


<3
