### ISSUE TITLE
Typed Styles - API design.

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#332]
- We should design something like https://github.com/seed-rs/seed/issues/312#issuecomment-565832751 for styles.

**Comment by MuhannadAlrusayni** [comment]
What about something similar to this [`Style`](https://docs.rs/khalas/0.1.1/khalas/css/struct.Style.html). I use this in Khalas and I use the same way with [events](https://docs.rs/khalas/0.1.1/khalas/events/struct.Events.html). If you guys like this way I can make PR with these changes in Seed so they become part of Seed ?

**Comment by MartinKavik** [comment]
Khalas looks very nice, but it seems more like a library than super simple wrapper for CSS properties.
The idea is - Seed provides basic foundation for attributes, events, styles and elements/tags and you can use it to build libraries. 
This foundation should be auto-generated, consistent, non-opinionated and typed & simple as much as possible. Example of styles (consistent with the draft design for atttributes):
```rust
div[
    S.position.absolute(),
    S.left(px(30)),
    S.top(px(50)),
]
```
And with Khalas:
https://docs.rs/khalas/0.1.1/khalas/css/struct.Style.html#method.position
```rust
div![
    Style::default()
        .position(|conf| {
            conf.position(|conf| {
                conf.absolute().top(px(50)).left(px(30))
            })
        })
]
```

**Comment by MartinKavik** [comment]
1. draft:
```rust
div![
    S.position().absolute(),
    S.left().px(30),
    S.border().style(|s| (s.solid(), s.dotted())),
]
```

**Comment by MartinKavik** [comment]
Closing in favor of https://github.com/seed-rs/seed/issues/413
