### ISSUE TITLE
Input type range value bug

### ISSUE THREAD

**Issue by TatriX** [seed-rs/seed#335]
```rust
input![
            attrs![
                At::Value => "400",
                At::Type => "range",
                At::Min => "100",
                At::Max => "800",
                At::Step => "50",
            ]
        ]
```
Rendered: 
![image](https://user-images.githubusercontent.com/703150/72523233-a769d180-385f-11ea-8003-c7115fb81ac2.png)

while it should look like this:
![image](https://user-images.githubusercontent.com/703150/72523205-991bb580-385f-11ea-928c-e2a7842304e0.png)

To get a proper behavior `value` need to be placed after `step`:
```rust
input![
            attrs![
                At::Type => "range",
                At::Min => "100",
                At::Max => "800",
                At::Step => "50",
                At::Value => "400",
            ]
        ] 
```
while it should work independent of attributes order.

**Comment by MartinKavik** [comment]
You can try to play a little bit with this line: https://github.com/seed-rs/seed/blob/5d94d966fec97d7b4dfa841259f87fa5dbcb831a/src/browser/dom/virtual_dom_bridge.rs#L252
Maybe Seed tries to set a value through direct call, before the other attributes are patched. And it causes some wierd side-effects. Just my first guess. 

Or could you post a minimal example?

**Comment by TatriX** [comment]
Both `master` & `0.5.1`.
Based on `examples/counter`:
```rust
//! A simple, cliché example demonstrating structure and syntax.
//! Inspired by [Elm example](https://guide.elm-lang.org/architecture/buttons.html).

// Some Clippy linter rules are ignored for the sake of simplicity.
#![allow(clippy::needless_pass_by_value, clippy::trivially_copy_pass_by_ref)]

use seed::{prelude::*, *};

// ------ ------
//     Model
// ------ ------

type Model = i32;

// ------ ------
//    Update
// ------ ------

enum Msg {
    Increment,
    Decrement,
}

fn update(msg: Msg, model: &mut Model, _: &mut impl Orders<Msg>) {
    match msg {
        Msg::Increment => *model += 1,
        Msg::Decrement => *model -= 1,
    }
}

// ------ ------
//     View
// ------ ------

fn view(model: &Model) -> Node<Msg> {
    div![
        button![ev(Ev::Click, |_| Msg::Decrement), "-"],
        div![model.to_string()],
        button![ev(Ev::Click, |_| Msg::Increment), "+"],
        hr![],
        input![
            attrs![
                At::Value => "400",
                At::Type => "range",
                At::Min => "100",
                At::Max => "800",
                At::Step => "50",
            ]
        ]
    ]
}

// ------ ------
//     Start
// ------ ------

#[wasm_bindgen(start)]
pub fn render() {
    App::builder(update, view).build_and_start();
}
```

**Comment by MartinKavik** [comment]
![attr_patching](https://user-images.githubusercontent.com/18517402/72598266-be67fc80-390f-11ea-9a39-4306034950d9.gif)
Value has to be set after Min & Max => setting attributes are order-sensitive and DOM API is horrible as usual so I can't find something like `Element::set_attributes` or `create_element_with_attributes`. 
Another alternative is to create the element from string - there are more options - https://stackoverflow.com/questions/494143/creating-a-new-dom-element-from-an-html-string-using-built-in-dom-methods-or-pro.
So we'll need to change this code https://github.com/seed-rs/seed/blob/master/src/browser/dom/virtual_dom_bridge.rs#L101-L131 and maybe https://github.com/seed-rs/seed/blob/master/src/browser/dom/virtual_dom_bridge.rs#L229-L292 (if we need it also for patching).

@TatriX Could you try to fix it once you have time?

**Comment by TatriX** [comment]
I'll be off for 2 weeks starting tomorrow. Will look afterwards if it steel be open.
