### ISSUE TITLE
Please add aria attributes from the HTML 5 specification

### ISSUE THREAD

**Issue by zakaluka** [seed-rs/seed#355]
The tags (with additional information) are provided at: https://www.w3.org/TR/html52/dom.html#state-and-property-attributes 

More information is also available at: https://www.w3.org/TR/wai-aria-1.1/

**Comment by MartinKavik** [comment]
- If I'm not wrong these are `attributes` and not `tags` - if so, please update the title and the description so it's not confusing for other readers, thanks.
- I'm writing Bootstrap library for Seed and there are many `aria*` attributes so I feel your pain.
- Seed element attributes are auto-generated from the online database. I hope the source for the data will be updated with this issue - https://github.com/seed-rs/seed/issues/312. You can read more about how it works here - https://github.com/seed-rs/seed/issues/312#issuecomment-565962781.

**Comment by zakaluka** [comment]
@MartinKavik  Thanks for the feedback and links.  The title has been changed.  I hope to see these items in the near future.

Will you be able to share the Bootstrap library you are creating or is that for a private / internal project?

**Comment by MartinKavik** [comment]
@zakaluka: Ad bootstrap library - it's a paid job for a client. They want to publish it in the future. The scope (how many components, utilities, etc. will be supported) isn't defined.
I want write also different abstraction for styles, so we will see.

**Comment by MartinKavik** [comment]
Merged into `master` (see referenced PR above).
