### ISSUE TITLE
Add `visibilitychange` event

### ISSUE THREAD

**Issue by akhilman** [seed-rs/seed#358]
Add `visibilitychange` to window events.
> The visibilitychange event is fired at the document when the content of its tab have become visible or have been hidden.

https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event

**Comment by MartinKavik** [comment]
Event API will be redesigned - https://github.com/seed-rs/seed/issues/331. And variants will be auto-generated from the online database (see https://github.com/seed-rs/seed/issues/312#issuecomment-565962781 if you want to know how it works).
Until the new API is designed & implemented feel free to create a PR with `visibilitychange` or create event from string (aka custom event) in your project.

**Comment by MartinKavik** [comment]
It's in `master`, closing.
