### ISSUE TITLE
Typo in seed-rs misc features page

### ISSUE THREAD

**Issue by akhilman** [seed-rs/seed#363]
![image](https://user-images.githubusercontent.com/180812/75088535-3fef2200-5581-11ea-806c-afaef9894684.png)
https://seed-rs.org/guide/misc-features

**Comment by akhilman** [comment]
Also in https://seed-rs.org/guide/server-integration `cargo.toml` starts with lowercase `c`.
![image](https://user-images.githubusercontent.com/180812/75088929-1258a780-5586-11ea-94ed-99f2505a2b41.png)

**Comment by akhilman** [comment]
Wrong repo.

**Comment by MartinKavik** [comment]
Note - I've also created some issues in wrong repos - I don't know if you need special permissions, but github can transfer issues from one repo to another. (I see button `Transfer issue` on this page in the right sidebar).

**Comment by akhilman** [comment]
I do not see such button.
