### ISSUE TITLE
Seed's UpdateEl::update method clashes with Itertools

### ISSUE THREAD

**Issue by rebo** [seed-rs/seed#370]
This issue was just reported on Discord #support by user BestRanar . When using itertools and iterators in seed views that have not been terminated with a `collect::<Vec<_>>()` there is a disambiguation compiler error generated from the seed macro.

```
error[E0034]: multiple applicable items in scope

note: candidate #1 is defined in an impl of the trait 'seed::virtual_dom::update_el::UpdateEl' for the type 'std::iter::FilterMap<_, _>'

note: this error originates in a macro outside of the current crate
```

Basically rust does not know whether to use Seed's `update` function or Itertools's `update`.  

Probably the best bet to fix is to change the name of Seed's view macro `update()` method to something like `seed_update()`.  The reason for this is that Seed's `update` is internal to the seed macros and in theory not a public api and Itertools is common enough that this clash will come up more frequently.

Another fix is to disambiguate directly in the seed macro, however this prevents implementation of custom UpdateEls by a user if needed.

The temporary fix to the above is to terminate iterators with a `collect()` if using itertools.

**Comment by MartinKavik** [comment]
- I have the exact problem (`itertools` clash) in one of my projects.
- I would rename `update` method to `update_el` so it corresponds with naming conventions and similar errors are easier to identify.
- I would call it with [fully quialified syntax](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name) to prevent this issue.
- I'll fix it.

Do you see any problems with the suggested solution?

**Comment by rebo** [comment]
`update_el` is good.

For fully qualified name syntax would perm fix but we might want to hold off for a bit.

This is because I am getting some milage out of self implementing update to allow dx improvements.

For instance the `bind` function you have works because I have implemented update locally on the return type of bind ( it just delegates update to an EventHandler and a Attr).  Other Dx improvements  could be made with further experimentation which I couldn't do if the method was called via fully qualified syntax. 

I'm thinking things like functions that set both style and inner node blocks (by returning a (Style, Node) typle) for a potential SeedUI.

**Comment by MartinKavik** [comment]
Ok, `update_el` should resolve it enough.

**Comment by MartinKavik** [comment]
(can be implemented once https://github.com/seed-rs/seed/issues/365 is resolved to prevent merge conflicts)
