### ISSUE TITLE
Typed Tags - Api design

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#374]
New `Tag` API to make it consistent with other element entities - [attributes](https://github.com/seed-rs/seed/issues/312#issuecomment-565832751), [events](https://github.com/seed-rs/seed/issues/331), [styles](https://github.com/seed-rs/seed/issues/332).

1. draft:
```rust
custom![
    T.custom("code-block"),
]
...
    T.h1(),
    T.div(),
```

**Comment by MuhannadAlrusayni** [comment]
It would be more readable if use something like `Tag` or `tag` instead of `T`.

**Comment by MartinKavik** [comment]
It's used basically only in `custom!` macro, so I chose `T` instead of `Tag` to make it consistent with other entities. I don't have strong opinion about it.
Other opinions?

**Comment by flosse** [comment]
> It's used basically only in `custom!` macro,

So the `h1!` and `div!` macros will kept?

**Comment by MartinKavik** [comment]
`h1`, `div!` use `Tag` under the hood. No changes for them.
Or do you have something else on you mind?

**Comment by flosse** [comment]
> `h1!`, `div!` use `Tag` under the hood. No changes for them.

ok :) So then I support your idea to align the `Tag` with `T` :)

> Or do you have something else on your mind?

no.

**Comment by MartinKavik** [comment]
Another reason to change `Tag` to `T` - `Tag` is very popular entity name, so there are often clashes between Seed's Tags and Tags from your business domain.

**Comment by MartinKavik** [comment]
Closing in favor of https://github.com/seed-rs/seed/issues/525.
