### ISSUE TITLE
class! improvements

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#375]
Suggested `class!` changes:
- [x] Rename `class!` to `C!` to improve readability and make it consistent with `A`, `S,` `E,` and `T`.
- [x] Accepts also `String` and other text types.
- [x] Don't write empty `class` to HTML, i.e. `class![]` shouldn't be rendered as `<div class>`.

---

_Note:_ We need to write `if_` function.

**Comment by MuhannadAlrusayni** [comment]
I wouldn't vote for renaming to `C!` since we use this macro only once per node.
I would agree for the other points.

**Comment by flosse** [comment]
> Suggested `class!` changes:
> * Rename `class!` to `C!` to improve readability and make it consistent with `A`, `S,` `E,` and `T`.

:-1: 

>  * Accepts also `String` and other text types.

:+1: 

> * Don't write empty `class` to HTML, i.e. `class![]` shouldn't be rendered as `<div class>`.

:+1:

**Comment by MartinKavik** [comment]
I have problems to read (longer) `view`'s because `class!` looks like element macros so it take me a while to decide if the given element has children or it has only `class` defined. The same for finding `class` attribute among other entities.
When I tried some options in source code, `C!` seems to me the most recognizable.

Counter arguments / other opinions?

**Comment by flosse** [comment]
Styles are key-value pairs for the attribute `style` (`<div style="name:property;" />`) so it makes sense to introduce a separate type `S` beside `A`. Event handlers are also special, so I can see why there is an `E`.
But `class` is just one of hundreds of attribute names (like `id` or so). So I would not expect a separate `C!` macro.
Of course it's a popular attribute so providing a convenient way to write it makes sense. But that's another bucket. Otherwise I would expect a `I!` for the popular `id` attribute, `X!` and `Y!` for the popular attributes `x` and `y` (in svg images), etc.

**Comment by MartinKavik** [comment]
I would rather use `A.class("..")` & `A.id("..")` and get rid of `class!` and `id!`. 
However I haven't found a reasonable way how to express class conditionals `class!["active" => active]` in `A.class(..)`.

**Comment by MartinKavik** [comment]
> But class is just one of hundreds of attribute names (like id or so). So I would not expect a separate C! macro.

```rust
div![
    id!("submit-btn"),
    class!["btn", "btn-primary", &my_classes, "active" => active],
    "Submit",
]
```

vs

```rust
div![
    A.id("submit-btn"),
    A.class(["btn", "btn-primary", &my_class, if_(active, "active")]),
    "Submit",
]
```
_Note:_ `if_` would we usable also with elements, event handlers, etc. - ie. `if_(cond, div![])` ~ `if cond { div![] } else { empty![] }`.

What do you think?

**Comment by MuhannadAlrusayni** [comment]
>  I haven't found a reasonable way how to express class conditionals class!["active" => active]

Another way to do it with function `class()`:
``` rust
    #[derive(From, Debug)]
    pub struct Class(Vec<Cow<'static, str>>);

    // impl UpdateEl for Class

    #[derive(From)]
    pub enum ClassArgument {
        #[from]
        Option(Option<Cow<'static, str>>),
        #[from]
        Str(Cow<'static, str>),
        #[from]
        VecOption(Vec<Option<Cow<'static, str>>>),
        #[from]
        Vec(Vec<Cow<'static, str>>),
        #[from]
        Conditional(Cow<'static, str>, bool),
    }

    pub fn class(arg: impl Into<ClassArgument>) -> Class {
        match arg.into() {
            ClassArgument::Option(Some(class)) => Class(vec![class]),
            ClassArgument::Str(class) => Class(vec![class]),
            ClassArgument::VecOption(classes) => {
                Class(classes.into_iter().filter_map(|class| class).collect())
            }
            ClassArgument::Vec(classes) => Class(classes),
            ClassArgument::Conditional(class, cond) if cond => Class(vec![class]),
            _ => Class(vec![]),
        }
    }

    impl From<(&'static str, bool)> for ClassArgument {
        fn from((class, cond): (&'static str, bool)) -> Self {
            Self::Conditional(class.into(), cond)
        }
    }

    impl From<(String, bool)> for ClassArgument {
        fn from((class, cond): (String, bool)) -> Self {
            Self::Conditional(class.into(), cond)
        }
    }

    impl From<String> for ClassArgument {
        fn from(source: String) -> Self {
            Self::Str(source.into())
        }
    }

    impl From<&'static str> for ClassArgument {
        fn from(source: &'static str) -> Self {
            Self::Str(source.into())
        }
    }

    impl From<Option<String>> for ClassArgument {
        fn from(source: Option<String>) -> Self {
            Self::Option(source.map(|v| v.into()))
        }
    }

    impl From<Option<&'static str>> for ClassArgument {
        fn from(source: Option<&'static str>) -> Self {
            Self::Option(source.map(|v| v.into()))
        }
    }

    impl From<Vec<&'static str>> for ClassArgument {
        fn from(source: Vec<&'static str>) -> Self {
            Self::Vec(source.into_iter().map(|v| v.into()).collect())
        }
    }

    impl From<Vec<String>> for ClassArgument {
        fn from(source: Vec<String>) -> Self {
            Self::Vec(source.into_iter().map(|v| v.into()).collect())
        }
    }

    impl From<Vec<Option<&'static str>>> for ClassArgument {
        fn from(source: Vec<Option<&'static str>>) -> Self {
            Self::VecOption(source.into_iter().map(|v| v.map(|v| v.into())).collect())
        }
    }

    impl From<Vec<Option<String>>> for ClassArgument {
        fn from(source: Vec<Option<String>>) -> Self {
            Self::VecOption(source.into_iter().map(|v| v.map(|v| v.into())).collect())
        }
    }

```

Usage:
``` rust
let attrs = vec![
    class("foo"),
    class("foo".to_string()),
    class(Some("foo")),
    class(vec!["foo", "boo"]),
    class(("foo_true", true)),
    class(("foo_false", false)),
    class(vec![Some("foo"), None, Some("boo")]),
];
// [Class(["foo"]), Class(["foo"]), Class(["foo"]), Class(["foo", "boo"]), Class(["foo_true"]), Class([]), Class(["foo", "boo"])]
println!("{:?}", attrs);
```

**Comment by MartinKavik** [comment]
OT: @MuhannadAlrusayni please use gist or Rust playground for long code snippets.

**Comment by TatriX** [comment]
I wonder whether it's possible to do something like this:
```rust
node![div, ".foo.bar", ...]
// or maybe
node![div, ["foo", "bar" => active], "Text", span!["Hi"]]
```

**Comment by MuhannadAlrusayni** [comment]
@TatriX I believe we can achieve this, but I don't think it will more readable than what we have now, imagine something like this:
``` rust
node![
    div, .foo #foo#bar
    node![
        h1, .page-title #title,
        "Page Title"
    ],
]
```
vs
``` rust
div![
    class!("foo", "bar"),
    id!("foo"),
    h1![
        class!("title"),
        id!("page-title"),
        "Page Title"
    ],
]
```

**Comment by flosse** [comment]
BTW: on the backend I really like to use [maud](https://maud.lambda.xyz/), so I'd love to use it on the frontend too :)

```rust
div #submit-btn .btn .btn-primary class=(&my_class) class="active"?[active] {
  "Submit"
}
```
vs
```rust
div![
    A.id("submit-btn"),
    A.class(["btn", "btn-primary", &my_class, if_(active, "active")]),
    "Submit",
]
```

**Comment by MartinKavik** [comment]
- We can't use `maud` now because it requires nightly.
- I can imagine it would scare beginners - e.g. React developers would have to learn TEA, Rust, Maud and Seed API at once.
- I use consts for classes (e.g. `C.btn`) and I want to integrate something like this to Seeder. I don't know Maud very much, but it seems that it's not designed for similar cases.
- Is it possible to handle special things like element references or elements keys with Maud?
- Both examples ^ seems pretty comparable to me, but I see your point - you can share the same template system with the backend and eyes are able to quickly identify symbols like `#` and `.` as ids and classes because we are used to see them often.
- I started to work on Seed because I was annoyed by Yew's html! macro - very cryptic errors, need to learn another language, not flexible enough..
- I'm afraid it'll make Seed code-base more complex and it would be another dependency and also key dependency without our direct control.
- I don't know about Maud IDE support I'm afraid that it will be always worse then Rust's native syntax.
- I can imagine that other people or even you will want to use another template system in the future (backend frameworks will pick different template lib; maintainer will deprecate Maud; there will be better template libs, etc.).
- Is it possible to transform Maud template to Seed "template"? E.g. Does Maud have some parsers / convertors / plugins for it?

**Comment by rebo** [comment]
So in my opinion the key thing for Seed's success has to be developer experience over and above all other considerations bar correctness and sensible performance.

My concern about the below is that it's very noisy, messy and annoying to write out every single time I want a class (which I almost always do for every element):

```rust
A.class(["btn", "btn-primary", &my_class, if_(active, "active")]),
```
Whilst it is conceptually and structurally true that `class` is just another attribute it is pretty much the most commonly used one. Therefore, from the developer experience there is a reason to special case it.  

Think about a developer experienced in JSX they are used to something simple like `<div className = "btn">` we dont want to raise the barrier to new developers because they might look at all the extra syntax and nope out.

Personally I think

```rust
C!["x", "y", &my_class, if_(active, "active")];
```

is far more readable and maintainable than this: 

```rust
A.class(["btn", "btn-primary", &my_class, if_(active, "active")]),
```

I think the `C!` version is far easier to scan so I can pick out the relevant classes.

So my solution is to allow both.  `A.class ...` would be allowed precisely because `class` is 'just another attribute' but `C!` is effectively syntactic sugar to clean this up.

I definitely agree with using `if_` though, it reads correctly in terms of english as well.

```rust
 if_(active, "active")
```
if active is true then use the "active" class.

**Comment by TatriX** [comment]
I think `if_` looks a bit ugly, so maybe `when`/`unless` instead? 
```rust 
c!["x", "y", &my_class, when(active, "active"), unless(hidden, div![])];
```

**Comment by TatriX** [comment]
Here's another option with several different types of syntax for attributes:
```rust
div![
     class => ["x", "y", &my_class, when(active, "active")],
     id = "foo",
     :style ["float: "left],
     onclick: |_| Msg::Click,
     "Text here",
     span!["quux"],
];
```
Tag macro can contain either `impl UpdateEl` or `attribute_name DELIMITER $value`.

**Comment by TatriX** [comment]
Personally I like `class: ["foo"]` syntax.
- It's easy to type and search/grep for relevant attributes: `grep 'class:' *.rs`
- Element creation looks similar to struct creation:
```rust
div![
    class: ["foo", when(active, "bar")],
    id: "quux",
    "Hi there",
   span!["hi"],
]
```
Sugar for
```rust
let div = Div{
 class: vec![Some("foo"), if active { Some("bar") } else { None }],
 id: Some("quux"),
 children: vec![
    Element::Text("Hi there"),
    Element::Node(Span{children: vec!["hi".into()], ..default::Default()})
 ],
 ..default::Default()
};
```

**Comment by MartinKavik** [comment]
> I think if_ looks a bit ugly, so maybe when/unless instead?

- `when` looks good.
- `unless` is redundant and I remember mental exercising and bugs because of this keyword in CoffeeScript...  I'd rather use `when(!active, "active")` or `when(not(active), "active")` if it's too easy for you to overlook `!`. 
Equivalent would be `if_not(` - here the underscore isn't so ugly and it's similar to `when(not`.

> class: ["foo", when(active, "bar")],
    id: "quux",

I agree it's very readable, but autocomplete isn't applicable for it at all and it can get annoying when you want to use attributes with enum of values, e.g. `autocomplete: Autocomplete::Off` (verbose and you have to import enum) or `autocomplete: off` (is `off` variable or variant?).
Perhaps I would rather choose existing template system like @flosse suggested instead of it.

**Comment by rebo** [comment]
Thumps up for `when(condition, attribute)`.

**Comment by flosse** [comment]
I'm sorry for the late response

> * We can't use `maud` now because it requires nightly.

yes, that's right.
 
> * I can imagine it would scare beginners - e.g. React developers would have to learn TEA, Rust, Maud and Seed API at once.

I think it's a bit scary anyway and there is not much difference between learning macros of seed or maud; both are kind of a DSL.
 
> * Is it possible to handle special things like element references or element keys with Maud?

no, I don't think so.
 
> * Both examples ^ seems pretty comparable to me, but I see your point - you can share the same template system with the backend and eyes are able to quickly identify symbols like `#` and `.` as ids and classes because we are used to see them often.

It's not better or worse, it's possible just a personal preference.

> * I started to work on Seed because I was annoyed by Yew's html! macro - very cryptic errors, need to learn another language, not flexible enough..

I see.
 
> * I'm afraid it'll make Seed code-base more complex and it would be another dependency and also key dependency without our direct control.

Absolutely. I didn't mean to actually depend on maud but it's probably an interesting inspiration.

> * I don't know about Maud IDE support, but I'm afraid it will be always worse than for Rust's native syntax.

I agree! 

>     * Is it possible to transform Maud template to Seed "template"? E.g. Does Maud have some parsers / convertors / plugins for it?

Oh, I don't think so.

So again, my comment was meant to be an inspiration :)

**Comment by flosse** [comment]
That's my personal ranking for conditional expressions:
1. `when(not(active), "active")`
2. `when(!active, "active")`
3. `if_(!active, "active")`
4. `unless(active, "active")` ... I also remember the CoffeeScript's `unless` bugs, so let's avoid it!

**Comment by MartinKavik** [comment]
Implemented in https://github.com/seed-rs/seed/pull/390
  - `when` changed to `IF!` (see reasons in that [PR](https://github.com/seed-rs/seed/pull/390)).
  - `not` added.
  - `C!` added and accepts types defined in `to_classes.rs`.

**Comment by sabine** [comment]
I'm fine with the semantics of `C!` as it is now, but I believe in discoverability. As a new developer coming to Seed, I shouldn't have to guess and look up what `C!` means.

When it's named `class!`, the likelihood of a newcomer having a great onboarding experience is increased, because HTML looks so similar.
Ideally someone familiar with either Elm, React, Angular should be able to read and understand the TodoMVC example with only minimal commentary.
