### ISSUE TITLE
Improve error message when Model doesn't implement Default

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#376]
"... and `AfterMount` doesn't create `Model` instance explicitly".

Should we add something like `assert` somewhere to give the user a reasonable error message?
Ideas?

**Comment by mikeyoz** [comment]
Here's the error:
```
error[E0599]: no method named `build_and_start` found for type `seed::app::builder::Builder<Msg, Model, seed::virtual_dom::node::Node<Msg>, seed::app::UndefinedGMsg, seed::app::builder::init::UndefinedInitAPI>` in the current scope
  --> src/lib.rs:35:32
   |
35 |     App::builder(update, view).build_and_start();
   |                                ^^^^^^^^^^^^^^^ method not found in `seed::app::builder::Builder<Msg, Model, seed::virtual_dom::node::Node<Msg>, seed::app::UndefinedGMsg, seed::app::builder::init::UndefinedInitAPI>`
   |
   = note: the method `build_and_start` exists but the following trait bounds were not satisfied:
           `seed::app::builder::init::UndefinedInitAPI : seed::app::builder::InitAPI<Msg, Model, seed::virtual_dom::node::Node<Msg>, seed::app::UndefinedGMsg>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```

**Comment by TatriX** [comment]
I'm sure I've seen this error before, but right now I'm not sure how can I reproduce it. Could you please add an example?

**Comment by MartinKavik** [comment]
@TatriX You were asking me about it some time ago if I remember correctly :) How to repro - make sure your `Model` doesn't impl `Default` and don't use `after_mount`.

---

I did quick research.
I recommend to remove the code that represents the deprecated app builder API as the first step, because it makes code pretty complex.
2nd step: Implement two `build_and_start` functions. It's not possible directly on `Builder` so we have to add an extra `trait` for it. The first function will build and start the app in the standard way, the second one will contain `compile_error!("Hey, I don't know how to create Model!")`.
(I'm not sure if it's doable and the best way, other opinions welcome.)

**Comment by MartinKavik** [comment]
New API for `App` initialization - https://github.com/seed-rs/seed/issues/382 - implemented in PR https://github.com/seed-rs/seed/pull/388. It's much simpler so it should eliminate all cryptic compiler errors.
