### ISSUE TITLE
Template for GUIs with seed+gotham - potential use case/example

### ISSUE THREAD

**Issue by liketechnik** [seed-rs/seed#379]
Hey guys,
after posting my project on reddit, someone proposed to inform you guys about my project.
The goal of my project is to provide an 'electron like' template, that allows to create local/desktop browser GUIs with access to the local filesystem (e. g. without the usual browser restrictions). I want this for a project where I want to render latex formula in my GUI and save a lot of files.
Using seed, [gotham](https://gotham.rs/), [rust-embed](https://github.com/pyros2097/rust-embed) and [web-view](https://github.com/Boscop/web-view) the template now compiles into a single, os independent binary, that directly opens in its own window.

Let me know your thoughts on the project and thanks for an amazing library :)

P. S.: The project's repository is at: https://gitlab.com/liketechnik/local-gui-seed-gotham

**Comment by rebo** [comment]
This looks pretty awesome I'm going to try it tonight. Thanks.

**Comment by MartinKavik** [comment]
Nice! I'll test it more once it's buildable on WIndows.
I think it would be nice to have it in https://github.com/seed-rs/awesome-seed-rs.

**Comment by MartinKavik** [comment]
@liketechnik Feel free to post a new topic on our forum or chat once there are some news / updates.
