### ISSUE TITLE
ElRef should derive Debug (?)

### ISSUE THREAD

**Issue by dodomorandi** [seed-rs/seed#387]
I just noticed that `ElRef` does not impl `Debug`. Is that something expected?

**Comment by rebo** [comment]
What would you like it to print?

**Comment by dodomorandi** [comment]
I think that even the type with an ellipsis or similar would be ok. Something like `ElRef<HtmlDivElement> {...}`.

My main concern is the boilerplate of manually implementing `Debug` for models with one or more `ElRef` in it. What do you think?

**Comment by rebo** [comment]
Yes that makes sense. You might want to write up a PR for it. Especially when Elrefs are used in models.

A work around for the boilerplate in the mean time is new type `ElRef` implement deref for that and then store that in the model instead of the ElRef. Not pretty but at least you dont have to write loads of boilerplate until it's fixed.

**Comment by dodomorandi** [comment]
Perfect! I will send a PR in these days!

**Comment by MartinKavik** [comment]
I've tried to derive `Debug` to `ElRef` and print `Model` from `canvas` example - results:
Default / empty `ElRef`:
```rust
Model {
    fill_color: A,
    canvas: ElRef {
        shared_node_ws: SharedNodeWs(
            RefCell {
                value: None,
            },
        ),
        phantom: PhantomData,
    },
}
```
`ElRef` with set element during VDOM patching (i.e. after render):
```rust
Model {
    fill_color: A,
    canvas: ElRef {
        shared_node_ws: SharedNodeWs(
            RefCell {
                value: Some(
                    Node {
                        obj: EventTarget {
                            obj: Object {
                                obj: JsValue(HTMLCanvasElement),
                            },
                        },
                    },
                ),
            },
        ),
        phantom: PhantomData,
    },
}
```
Is it ok for you guys?

**Comment by dodomorandi** [comment]
I think it is fine! There is a lot information that _probably_ is not necessary, but I would expect to see it using `Debug`.
