### ISSUE TITLE
Allow to return () in handlers which currently return only Msg

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#391]
Allow to return () in handlers which currently return only Msg. 
Important for Hooks integration and usable also for handlers which contain only side-effects.

- Implementation with panics for stable Rust - https://gist.github.com/MartinKavik/36a96f28b9bad76d6cb7141946f5f716
- Implementation with compile-time validation for nightly Rust - https://gist.github.com/MartinKavik/918ff345f1655eb32eb47090ecc73cd8.
   - It needs `#![feature(optin_builtin_traits)]` or [mutex_traits](https://github.com/withoutboats/rfcs/blob/mutex_traits/text/0000-mutex_traits.md) or negative trait bounds or conditional bounds or more advanced `specialization`.

**Comment by rebo** [comment]
This is quite an important developer experience improvement and greatly simplifies commands or messages that do not need further processing.

For instance without this enhancement a callback that updates a hook state variable (e.g. `counter`) would need something like this:

```rust
mouse_ev(Ev::Click, |_| { 
   counter.update(|&c| c+=1);
   Msg::default()
});
```

with `Msg` implementing `Default` and that leading to a no-op.

With the enhancement we can simply do : 

```rust
mouse_ev(Ev::Click, |_|  counter.update( |&c| c+=1 ) );
```

or with a simple helper function: 

```rust
on_click( || counter.update( |&c| c+=1 ) );
```

**Comment by MartinKavik** [comment]
Also I can't use `orders.subscribe` for internal Seed calls because I can't crate `Msg` instances => it's blocker for other issues - e.g. routing improvement.
