### ISSUE TITLE
Proposal: Support Option for Markdown to HTML conversion

### ISSUE THREAD

**Issue by liketechnik** [seed-rs/seed#392]
Quoting from the [pulldown-cmark description](https://docs.rs/pulldown-cmark/0.7.0/pulldown_cmark/):

> By default, only CommonMark features are enabled. To use extensions like tables, footnotes or task lists, enable them by setting the corresponding flags in the Options struct.

The ```md!``` macro only takes one parameter, which is the markdown as a string. For my markdown, I need these extensions, so at the moment I have to import pulldown_cmark into my project, do the conversion from markdown to HTML manually and use the result with ```raw!```.

Would you be open to somehow make it easier to adjust the options for the conversion? My current idea is to re-export the options struct from pulldown-cmark and have the macro optionally take an instance of that struct; although I never worked with macros in rust.

**Comment by MartinKavik** [comment]
It looks like there are only 4 [options](https://docs.rs/pulldown-cmark/0.7.0/pulldown_cmark/struct.Options.html). Do you think there will be some performance problems when we enable them all by default?

**Comment by liketechnik** [comment]
My guess is that it wouldn't have much, if any, impact on performance, because these options seem to be about specification compliance and not about disabling/enabling features with huge impact on performance. But I can only guess here.

**Comment by MartinKavik** [comment]
Ok, could you create a PR to enable these options?
Also I would be glad if you add an example - `/examples/markdown` - where you use these new features. Seed's examples is learning material for new users and also work as integration tests.
Thanks!

**Comment by liketechnik** [comment]
Yes, would be happy to do that.
