### ISSUE TITLE
Can we remove `'static` lifetime bound from Node/El ?

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [seed-rs/seed#394]
Hi, I was wondering why there is `'static` bound  in `Node<Ms: 'static>` and `El<Ms: 'static>` types, after checking I was not able to find their need.

Can we remove `'static` bound ?
why I need to do so? because when I want to create elements that contains `Node<Ms>` in it I have to write that bound every where (e.g. [Buutton](https://malrusayni.gitlab.io/khalas/khalas/el/control/button/struct.Button.html)).

If we cannot remove the bound for any reason, then I think we can move it to the impl block, so any type contains `Node<Ms>` in it would not need to write the bound.

Or there is better way to solve this issue ?

**Comment by MartinKavik** [comment]
See https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/closure/struct.Closure.html and https://github.com/rustwasm/wasm-bindgen/issues/1914. 
^ it's probably the main reason. If you are able to remove that restriction and not negatively affect public API, I would be happy to merge it.

**Comment by MartinKavik** [comment]
Also it's probably needed for the `Effect` queue.

**Comment by MuhannadAlrusayni** [comment]
I just removed the bound .. and things seems to work fine.
