### ISSUE TITLE
How to Graphql?

### ISSUE THREAD

**Issue by frederikhors** [seed-rs/seed#400]
I'm new to Rust and Seed (amazing project!).

I'm wondering if there is something "similar to" or useful "to use" for https://github.com/apollographql/apollo-client.

I need to use Graphql, how to?

**Comment by MartinKavik** [comment]
There are some GraphQL libs but I didn't have a reason to write an example - until now. 
So.. what does `I need to use Graphql` mean? I.e. how would like to use it / what backend do you have?

**Comment by frederikhors** [comment]
My backend is Graphql (apollo server).

**Comment by MartinKavik** [comment]
I've created a GraphQL example:
![graphql_example](https://user-images.githubusercontent.com/18517402/77623076-c069bf80-6f3f-11ea-9528-cf20782fca5a.gif)
- GraphQL queries and schemas are parsed and validated by Rust macros. Rust macros also generate Rust code from them so everything is typed and checked. 
- Link to `/examples/graphql`: https://github.com/seed-rs/seed/tree/master/examples/graphql
- GraphQL playground: https://countries.trevorblades.com/ (the same like the API url)
- Backend repository - https://github.com/trevorblades/countries
- Related issue in BE repo - https://github.com/trevorblades/countries/issues/14

**Comment by frederikhors** [comment]
Amazing! Really!

I think now we only miss a caching layer like https://www.apollographql.com/docs/react/caching/cache-configuration/ and https://github.com/apollographql/apollo-cache-persist.

**Comment by MartinKavik** [comment]
I'm glad you like it.

This example uses [graphql-client](https://github.com/graphql-rust/graphql-client). There are some cache-related issues - https://github.com/graphql-rust/graphql-client/issues/34 and https://github.com/graphql-rust/graphql-client/issues/89.
Also `graphql-client` is a project from [graphql-rust](https://github.com/graphql-rust) org with active development on many projects so I assume there will be cache support in the future.

I've done some little contributions to Elm and Elixir GraphQL libs but I don't have too much experience with it. If you have time you can help `graphql-client`'s creators or at least add comments into their issues so they know what their users want.

**Comment by MartinKavik** [comment]
@frederikhors If you think your original question `How to Graphql?` has been answered, please close the issue. If you have some other questions or something about the example isn't clear / some Rust things doesn't make sense to you - you can write on our chat or forum.

**Comment by MartinKavik** [comment]
I hope the question has been answered.
No response for a week, closing,
