### ISSUE TITLE
Convert `Node<Msg>` to `String`

### ISSUE THREAD

**Issue by nlinker** [seed-rs/seed#414]
Hello!

Let me ask a question on the API. I have a trouble with the debugging and testing code.
One of the problem is that what the appropriate method to convert some `Node` (or vector of `Node`-s) to nicely indented String, e.g.
```
let node: Node<Msg> = div![
        class![ "my-class-1", "my-class-2" ],
        button![ev(Ev::Click, |_| Msg::Decrement), "-"],
        div![model.to_string()],
        button![ev(Ev::Click, |_| Msg::Increment), "+"],
    ];
println!("{}", node._???_());
```
What to do here to print `<div class="my-class-1 my-class-2">...</div>`?

Thanks.

**Comment by MartinKavik** [comment]
I'm afraid that implementation of `Node` -> `String` "freezed" - https://github.com/seed-rs/seed/issues/294.
And it's not top priority for me now, so not ETA unfortunately.

**Comment by MartinKavik** [comment]
So we use `log!(node)`  (it's basically `println!("{:#?}", node)` + `console.log`.

**Comment by nlinker** [comment]
I see, thanks for the answer.
