### ISSUE TITLE
Url::(en/de)code

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#424]
Add (?):
- `Url::decode`
- `Url::decode_component`
- `Url::encode`

Or do it automatically? How other libraries / languages / frameworks handle it?

**Comment by power-fungus** [comment]
Currently, I could use `Url::path_decoded() -> Result<Vec<String>, _>`. The output type could also be an iterator. Since url-decoding can fail, the error would need to be caught in some way.

**Comment by MartinKavik** [comment]
I've modified routing / `Url` behavior a bit (PR #542, #541) - urls are automatically decoded and encoded now, including hash. `Url` has methods ` decode_uri_component` and `encode_uri_component` that are slim wrappers around their JS counterparts. However you shouldn't need them in practice.
