### ISSUE TITLE
perform_cmd issue

### ISSUE THREAD

**Issue by crusadergo** [seed-rs/seed#477]
Hi there! I got some problems with perform_cmd method. The project compiles successfully, but when using this method, I get the following error in the browser console:

![image](https://user-images.githubusercontent.com/5359450/83908204-5d7e7b00-a76f-11ea-83cf-f16aa52b9c47.png)

My code: 
![image](https://user-images.githubusercontent.com/5359450/83908341-a0d8e980-a76f-11ea-969a-c933fc4f266b.png)

I hope for your help. Many thanks!

**Comment by MartinKavik** [comment]
It looks like you are using two messages - `app::Msg` and `Msg` - try to use only one to resolve this error. 

_Note:_ It's a runtime error because current stable Rust is not expressive enough. We have prepared compile-type solution once one Rust feature is stabilized.

**Comment by crusadergo** [comment]
Thank you! I'll try
