### ISSUE TITLE
Fetch API since 0.7.0

### ISSUE THREAD

**Issue by mankinskin** [seed-rs/seed#483]
Hi I am trying to figure out how to use the new fetch API in version 0.7.0.
My problem is that FetchError does not implement Clone, but Response::json takes a &self, so I can not return a Result<T, FetchError> from a fetch future:
```
pub fn fetch_all_users(session: UserSession) -> impl Future<Output = Result<Vec<Entry<User>>, FetchError>>
{

    fetch(
        Request::new("http://localhost:8000/api/users")
            .header(Header::authorization(&format!("{}", session.token)))
            .method(Method::Get)
    )
    .map(|result: Result<Response, FetchError>| {
        result.and_then(Response::check_status)
    })
    .and_then(|response| response.json()) // << cannot return value referencing function parameter `response`
}
```

The [docs](https://docs.rs/seed/0.7.0/seed/browser/fetch/struct.Response.html#method.check_status) show this snippet: 
```
fetch(url)
    .map(|result| result.and_then(Response::check_status))
    .and_then(Response.json)
    .map(Msg::Fetched)
```
Which I assume is supposed to be using `Response::json`, but this does not work, because `Response::json` requires a reference to a Response.

My question is how this API is supposed to be used.

**Comment by MartinKavik** [comment]
That comment is a relic from pre-async/await era, sorry for that, I'll fix it.

It's often a pain to work with `Future` combinators and there are some limitations. I would write your example this way: https://github.com/MartinKavik/seed/blob/demo/fetch_all_users/examples/counter/src/lib.rs

**Comment by MartinKavik** [comment]
Snippet in that comment will be removed soon: https://github.com/seed-rs/seed/pull/484

I'll try to explain `Fetch` API and related stuff in the next example in guides: https://seed-rs.org/0.7.0/app_3_auth

**Comment by mankinskin** [comment]
@MartinKavik Thank you so much!
