### ISSUE TITLE
How to set the value on "number" input type

### ISSUE THREAD

**Issue by tmbull** [seed-rs/seed#486]
Hi, first of all thank you for creating `seed`! I have been a fan of `elm` for a while, so I was happy to find this simple `elm-like` WASM framework for Rust. 

I have been fighting an issue with "number" inputs for the last couple of hours. The issue I'm having is that I have been unable to find a way to both initialize a "number" input and also maintain invalid input in the input. The following example demonstrates the issue:

```rust
use seed::{prelude::*, *};

fn init(_: Url, _: &mut impl Orders<Msg>) -> Model {
    Model::default()
}

type Model = String;

enum Msg {
    Set(String)
}

fn update(msg: Msg, model: &mut Model, _: &mut impl Orders<Msg>) {
    match msg {
        Msg::Set(str) => *model = str
    }
}

fn view(model: &Model) -> Node<Msg> {
    div![
        input![
            attrs![
                At::Type => "number",
                At::Value => model,
            ],
            input_ev(Ev::Input, Msg::Set),
        ]
    ]
}

#[wasm_bindgen(start)]
pub fn start() {
    App::start("app", init, update, view);
}
```
This works for the most part, except that typing an invalid number (for example, `10.0.0`) into the field will cause the content to reset. This is jarring from a UX perspective. I would rather have form validation and allow the user to correct their input. Commenting out the `At::Value => model,` line will allow the input to maintain invalid text. However, there is then no way to initialize the value in the view.

I added a couple of `log!` statements, eg:

```rust
        Msg::Set(str) => {
            log!("msg", str);
            *model = str
        }
```
I found that `str` is the empty string if string is not a valid decimal number. I'm not sure if this is a behavior of `seed` or the browser itself. Changing the input type to "text" will resolve this issue. However, I prefer the "number" input type because it seems to be the most reliable way to get a numeric keyboard on mobile browsers. Any direction is appreciated.

**Comment by MartinKavik** [comment]
Yeah, `input` + `number` is another native "funny" element. You can't get invalid value from the field directly. You even can't write (with some exceptions) an invalid value in some browsers (e.g. Chrome and Firefox behave differently) - see `Important` under `Using number inputs` in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number.

I would replace `input_ev(Ev::Input, Msg::Set)` with `input_ev(Ev::Change, Msg::Set)`. That way only valid input will be stored in `Model`. However the invalid value will be still rewritten on rerender/blur - maybe it's ok maybe not - depends on your requirements.

Another way would be to go almost fully imperative and leverage some native validation methods: https://github.com/MartinKavik/seed/blob/demo/number_input/examples/counter/src/lib.rs

**Comment by tmbull** [comment]
@MartinKavik Indeed, I was playing around with this yesterday in plain HTML/JS and found the same behavior. Considering this has nothing to do with `seed`, sorry for the noise. Thanks for the reply, and thanks for creating `seed`!

**Comment by MartinKavik** [comment]
>  Considering this has nothing to do with seed, sorry for the noise.

I think it was a very good question. Seed should mitigate as many HTML/JS issues as possible. However you found an example when it's not very easy. I don't have an idea how to extract an invalid value from `number input` without using custom elements in your case.
