### ISSUE TITLE
[Documentation] ElRef example uses AfterMount, which is soon to be removed from API

### ISSUE THREAD

**Issue by Ben-PH** [seed-rs/seed#493]
See [here](https://github.com/seed-rs/seed/blob/master/src/virtual_dom/el_ref.rs#L19)

**Comment by MartinKavik** [comment]
@Ben-PH Thanks! Could you fix it please? The code in that comment should be a part of https://github.com/seed-rs/seed/blob/master/examples/canvas/src/lib.rs

**Comment by Ben-PH** [comment]
Can do.
