### ISSUE TITLE
Quick way to style all elements of a html type?

### ISSUE THREAD

**Issue by mankinskin** [seed-rs/seed#495]
I have a question, that is, how would I go about styling all elements of a specific HTML kind (p, a, h1, ...) in seed?
For example, if I have a view function that renders a div with many paragraphs:
```
div![
    p![ "Subtasks:"],
    self.tasks().len(),

    p!["Members:"],
    self.members().len(),

    ...
]
```
How would I go on and define a style for all p items in this div, or globally?
Something like the css selector:
```
p {
    ...
}
```

**Comment by MartinKavik** [comment]
> how would I go about styling all elements of a specific HTML kind (p, a, h1, ...) in seed?

It's supported through [Seed Style](https://seed-style-hooks.netlify.app/style_home). We are polishing it and waiting for the next Rust version so we can start to integrate it into Seed. There is an example (probably a bit older) - [global_styles.rs](https://github.com/rebo/seed-style-quickstart-basic/blob/3ea84d887bd209cefe8aabbf20ab4023a243a2c2/src/global_styles.rs#L6-L13).

I'm sure @rebo (the author) will be able to correct me / provide a better answer.

**Comment by mankinskin** [comment]
@MartinKavik Thanks for the response and the great resource. And this entire project in general, great effort!

Where would I have found this by myself? I don't think there is any part of the docs or on the [awesome list](https://github.com/seed-rs/awesome-seed-rs). It would be helpful to have some kind of registry for ongoing projects related to seed.

**Comment by MartinKavik** [comment]
> Where would I have found this by myself?

E.g. https://seed-rs.org/0.7.0/attributes => `style!` => `Future`

I'm writing new docs for more than a month now and many important things (like the rest of the 3rd example, ongoing projects, migration guides, nice seed-rs.org UI, etc.) are still missing, we'll improved it piece by piece 🙂 Thanks for the idea!

**Comment by rebo** [comment]
Hi @mankinskin , 

Although fairly comprehensive, Seed Style is in alpha stage at the moment. The feature it relies on has just been stabalised into rust master and therefore will be in stable rust I believe in 1.46 (in 6 weeks or so). Therefore you would have to use nightly until then.

There are also a number of changes that have been made that may not be fully reflected in the quickstart. If you have any questions I am usually active on Seed discord.

For your use case you have a number of possible solutions using Seed Style:

You can use a global style and intialise it like this. You would usually call this function from the Seed `init` function:

```rust
pub fn global_init() {
    GlobalStyle::default()
        .style(
            "a,ul,li,div,p,h1,h2,h3,h4,li,dd,dt,button,label,input",
            s().font_family("'Lato',sans-serif")
                .webkit_font_smoothing_antialiased(),
        )
        .style("p", s().color("red")
        .activate_init_styles();
}
```

Which would make all `<p>` tags have red test.

However what might be better for you is this:

```rust
div![
    s().style_child("p").color(rgb(255,0.0)),
    p![ "Subtasks:"],
    self.tasks().len(),

    p!["Members:"],
    self.members().len(),

    ...
]
```

Which makes all direct `<p>` children of the div red. 

Alternatively you could use  : 

```rust
s().style_descendant("p").color(rgb(255,0.0)),
```

Which would apply to all descendants not just direct children.

Most properties are typed therefore you shouldnt need to use strings too much, but of course you can pass string values too all properties if you want.

**Comment by mankinskin** [comment]
Sounds perfect! Styling is not high priority for my app at this stage, so I will probably focus on other stuff until the style api becomes more stable. Thanks for the preview :)
