### ISSUE TITLE
[Enhancement] log! output to respect `\n` byte, (and other \ escapes)

### ISSUE THREAD

**Issue by Ben-PH** [seed-rs/seed#506]
When logging a pretty debug, instead of multi-line, you get something more like this:

```text
"Outer {\n    inner: Inner0 {\n        inner: Inner1 {\n            field_name0: \"value\",\n            field_name1: \"value\",\n            field_name2: MyType,\n        },\n    },\n}"
```

Ideally, it would be as you'd get from the console:
```text
"Outer {
    inner: Inner0 {
        inner: Inner1 {
            field_name0: "value",
            field_name1: "value",
            field_name2: MyType
        }
    }
}"
```

I'm no good with macros, so I wouldn't know where to start. I would happily work to assist directly, though. It would be nice to learn by working with someone on this.

**Comment by MartinKavik** [comment]
I don't know how to replicate your problem, please elaborate a bit.

I tried:
```rust
#[derive(Debug, Default)]
struct Outer(Inner);

#[derive(Debug, Default)]
struct Inner {
    field_a: i32,
    field_b: i32,
}

fn init(_: Url, _: &mut impl Orders<Msg>) -> Model {
    log!(Outer::default());
    ...
}
```
and the result looks as expected:
![image](https://user-images.githubusercontent.com/18517402/87993125-0c8dd080-caea-11ea-8eb1-5cdffc635b8c.png)

**Comment by Ben-PH** [comment]
Worked it out. I was using the `format!` macro out of habit.

Learning this, there's three options that come to mind: Leave it as is, change log! so that it removes the format! macro, or make a log_fmt! macro that does that.

I'd probably go for the first one, and add to the documentation that log! usage should be with comma separation rather than a format string.

If it's possible, maybe post `format!` expansion can map `\n` to the JS equivilant character when used inside `log!`? Even so, I suspect that wouldn't be the best way to interface with JS internals.

**Comment by MartinKavik** [comment]
I don't want to change/design better API for logging until ideally these two issues are resolved:
1. `Redirect println! (and dbg!) to console.log` - https://github.com/seed-rs/seed/issues/292
2. https://github.com/seed-rs/seed/blob/8d04fcde8a22f785fa20d28cb2f1a9b3b2d7e790/Cargo.toml#L37-L39

Another problem - do we want to use `console.log`? or `.info` or `.debug` or something else? Probably we should write/use a [web_sys::console](https://rustwasm.github.io/wasm-bindgen/api/web_sys/console/index.html) wrapper or/and a new Seed logger.

So there are some current Rust limitations and we can easily fall into the rabbit hole of the `console` and logging abstractions.

---

Until then `log!` for debugging and `error!` for error logging should be enough. However I would be glad if you want to improve the docs in the code to explain how to use these macros: https://github.com/seed-rs/seed/blob/8d04fcde8a22f785fa20d28cb2f1a9b3b2d7e790/src/shortcuts.rs#L483-L532

**Comment by Ben-PH** [comment]
I'm in agreement. Also, since coming across this, I've seen other little things crop up that makes it look like the specifications of how to display text are at odds between Rust and JS. Your rabbit-hole comment prompts me to think it might be something for a stand-alone project.

I'll close this issue, and re-open a new one for documentation, referring back to this.
