### ISSUE TITLE
[Documentation] Describe `log!` usage and link to it in `error!`

### ISSUE THREAD

**Issue by Ben-PH** [seed-rs/seed#508]
See #506

Currently, the output of `log!` is not Just Right™ due to manner in which Rust and JS interact (to my understanding). Though things are in a good place and usable, Rusty habits and assumptions about how to format for console, and what the output will look like _exactly_, can mislead the unaware `log!` user.

Getting it "Just Right" is likely out of scope. Outlining this in documentation should equip the user to be aware of the little quirks and plan accordingly. 

Expect a PR on this from me later today.

**Comment by flosse** [comment]
obsolete since v0.10.0
