### ISSUE TITLE
`cargo make verify` ignores compilation errors

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#517]
@sagiegurari 
I've found an issue probably related to the changes in this PR: `cargo make verify` passes even if there are examples with compilation errors. See task `Verify` in https://github.com/seed-rs/seed/pull/467/checks?check_run_id=985053859 - it shows errors but it doesn't kill verification.
My first tip is that `exec --fail-on-error cargo make --cwd ${example_root} ${task}` isn't working as expected. Could you look at it please? 

cc @TatriX

_Originally posted by @MartinKavik in https://github.com/seed-rs/seed/pull/509#issuecomment-674115293_

**Comment by sagiegurari** [comment]
I'll check it out. thamks.

**Comment by sagiegurari** [comment]
it was a bug in duckscript 'exec' command. its resolved now.
rerunning cargo install would get pull the fix (in this case, just rerunning the github action flow i guess).

**Comment by MartinKavik** [comment]
<img width=200 src="https://user-images.githubusercontent.com/18517402/90285027-595b9180-de73-11ea-94d4-4f72fba68f5a.png">

- Job - https://github.com/seed-rs/seed/pull/467/checks?check_run_id=986227899

_Note:_ We have to run `cargo install cargo-make --force` on local machines until the new `cargo-make` version is released, then standard `cargo install cargo-make` will be enough.

@sagiegurari Thanks! Closing.
