### ISSUE TITLE
GraphQL module

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#519]
Hi, I'm writing a tutorial for seed-rs.org and I'm just implementing a graphql module. It's quite app-specific and uses external library [cynic](https://crates.io/crates/cynic) but maybe it would be nice to rewrite it into a general Seed module in the future.

Also there is an older [graphl example](https://github.com/seed-rs/seed/tree/master/examples/graphql) based on [graphql_client](https://crates.io/crates/graphql_client) library.

What's your experience with Seed  & GraphQL and GraphQL in general? Is there something what would you like to add into the GraphQL module?

**Comment by benwis** [comment]
I'm wondering if Seed could integrate with async-graphql. I know they have extensions for actix, tide rocket, and probably more, That way we can leverage the tons of good work they've done.

**Comment by benwis** [comment]
Just now realizing you're building a graphql client library and not a server one. I'd vote for subscription support then :)
