### ISSUE TITLE
Orders is difficult to use in a trait object

### ISSUE THREAD

**Issue by techninja1008** [seed-rs/seed#530]
I'm trying to use `Orders` in a trait object, however such is proving difficult. This initially stems from the inability to use an `impl Trait` parameter for a trait object, however it ultimately comes down to the presence of the associated types on `Orders`.

To give more context, I'm trying to achieve the following trait:

```rust
pub trait Page {
    type Message: 'static;

    fn update<'a>(&mut self, msg: Self::Message, orders: <some Orders<Self::Message> type here>);

    fn view(&self) -> Node<Self::Message>;
}
```

This is so I can ultimately store a boxed page in my root model without having massive enums and match statements with options for each page in my app. This is a rewrite of an app originally in Elm, where the massive custom types and case-ofs became unmanageable.

I have some ideas on how `Orders` and family could be tweaked to support this type of use case, however I thought I'd first seek advice as I'm new seed.

**Comment by techninja1008** [comment]
Just thought I'd also say that you guys have done such an awesome job on seed. I've been using it for one day, and I'm already preferring it to Elm. It feels more mature to me, despite being much newer.

**Comment by MartinKavik** [comment]
`Orders` was designed specifically for TEA and we didn't want to introduce `Page` / `Component` trait because it would mean we would need to also introduce another layer of abstraction and patterns to support them. (Basically Elm-like philosophy that components are bad.)

However we know that TEA may cause a lot of boilerplate and it makes writing component libraries harder and non-business state may pollute Models so we are working on Hooks/Atoms - see https://seed-style-hooks.netlify.app/. It should be used to eliminate boilerplate.

But maybe none of those options is viable for your case and I prefer "example-driven development" so I would like to see your pain (Elm/Seed code) before I'll try to suggest a reasonable solution or start to design better Seed API that would help you.

**Comment by techninja1008** [comment]
> ... Basically Elm-like philosophy that components are bad

I thoroughly agree with this, as hidden state can often be a pain for various reasons. This is actually the reason why I'm less of a fan of Hooks/Atoms. The purpose for my trait is simply to act as a collection of the model (type the trait is `impl`ed by), view function, update function and message type for a specific page, in order to take advantage of rust's runtime dynamic typing to decrease complexity of my app.

**For additional context, here's some information about the app I'm rewriting:**

The app is an internal order management tool at the company I work for. As such, it is ridden with business logic and is constantly changing to meet the needs of the business.

Whilst rebuilding the app in rust, as part of this trial, I decided to experiment with how much I could abstract away common logic for handling various aspects relating to different pages. In our current (Elm) codebase, the name for one arbitrarily-chosen page is referenced 10 different places (specifically, different types/functions), not including "genuine" uses (such as inside of its own definition, and references/linking from other pages). This is a lot of overhead that can be solved with trait-based polymorphism as present in rust.

Here are some examples of those different places that this page is referenced:

* **Root model** - specifically, in an enum-equivalent of all the pages in the app.
* **View function** - in a massive case-of (match) statement that dispatches a view call to the current page based on the modle
* **Message type** - an entry in the enum to wrap all the messages coming from this page
* **Session function** - again, massive case-of statement that only forwards the call to a function specific to the current page
* **Change Route function** - takes an enum value that represents one of all the possible routes in the application, and calls the init function for that page to initialize its model - doesn't actually handle any of the routing
* **Update function** - similar to the view function

And more.

**In terms of avoiding this in the rust rewrite via a Page trait in my app:**

I have the following structs:

```rust
struct AnyPage<P>
where
    P: Page,
{
    token: Arc<u8>,
    page: P,
}

pub struct AnyMsg {
    token: Arc<u8>,
    msg: Box<dyn Any>,
}
```

With `AnyPage<P>` implementing `Page<Message=AnyMsg>` so that it can be wrapped up as `Box<dyn Page<Message = AnyMsg>>`. I also have a function to convert anything implementing Page into a boxed AnyPage.

`token` is just used as a little trick that abuses heap allocation so that a message from a previous instance of the same type of page will never be accidentally delivered to a new instance of it. It's created simply from `Arc::new(0)`, cloned to where appropriate and checked by using == on a pair of `Arc::as_ptr(token)`.

This then means I can have the following as my root model:

```rust
pub enum Model {
    LoadingConfig,
    LoadError(backend::Error),
    Loaded { config: Config, ctx: Context, page: Box<dyn Page<Message = AnyMsg>> },
}
```

And my Msg:

```rust
enum Msg {
    GotConfig(backend::Result<Config>),
    GotPageMsg(AnyMsg),
}
```

Update is then as simple as calling `page.update(msg)` with the page stored in the current model, with view being similar as `page.view().map_msg(Msg::GotPageMsg)`. All the other features described above could be implemented with additional functions on the trait, but I haven't got there as I was stumped by introducing Orders into the mix.

From poking through the seed codebase, my personal view on a suitable way to solve this would be to move the associated types on Order, and the functions that use them in their signatures (which from what I can tell might be an implementation detail leak?), to a separate trait. This would then allow the creation of an `OrdersQueue<Msg>` struct which `impl`s `Orders<Msg>` and queues up internally all the various callbacks it gets from the likes of `perform_cmd`, `notify`, `subscribe` etc. and can be mapped with a function to a different Msg type, and then finally submitted to another Orders implementation to action everything.

**Comment by MartinKavik** [comment]
What do you think about https://github.com/seed-rs/seed/pull/531 ? (You can clone it and run from the root by `cargo make start page_trait`).

**Comment by techninja1008** [comment]
Thanks for making the example, I've actually ended up using a different method, as it's highly likely the consumer of the Page trait objects in our application will be moved to a separate crate (for visual consistency between different internal applications). As such, using an Enum at all isn't really practical.

What I've done is write a `struct` called `SimpleOrders<Msg>` that acts as a queue for (most of) the things that `Orders` does, without any association with an `App`. Source:

```rust
pub struct SimpleOrders<Msg>
where
    Msg: 'static,
{
    orders: VecDeque<Order<Msg>>,
    should_render: Option<ShouldRender>,
}

enum Order<Msg> {
    Command(Pin<Box<dyn Future<Output = Option<Msg>>>>),
    Message(Msg),
    Notification(Notification),
}

impl<Msg: 'static> SimpleOrders<Msg> {
    pub fn new() -> SimpleOrders<Msg> {
        SimpleOrders {
            orders: VecDeque::new(),
            should_render: None,
        }
    }

    pub fn map<ToMsg: 'static>(
        self,
        mapper: impl (FnOnce(Msg) -> ToMsg) + Clone + 'static,
    ) -> SimpleOrders<ToMsg> {
        SimpleOrders {
            orders: self
                .orders
                .into_iter()
                .map(|order| match order {
                    Order::Command(future) => {
                        let my_mapper = mapper.clone();
                        Order::Command(Box::pin(future.map(|maybe_msg| maybe_msg.map(my_mapper))))
                    }
                    Order::Message(msg) => {
                        let my_mapper = mapper.clone();
                        Order::Message(my_mapper(msg))
                    }
                    Order::Notification(msg) => Order::Notification(msg),
                })
                .collect(),
            should_render: self.should_render,
        }
    }

    pub fn render(&mut self) -> &mut Self {
        self.should_render = Some(ShouldRender::Render);
        self
    }
    pub fn force_render_now(&mut self) -> &mut Self {
        self.should_render = Some(ShouldRender::ForceRenderNow);
        self
    }
    pub fn skip(&mut self) -> &mut Self {
        self.should_render = Some(ShouldRender::Skip);
        self
    }

    pub fn notify(&mut self, message: impl Any + Clone) -> &mut Self {
        self.orders
            .push_back(Order::Notification(Notification::new(message)));
        self
    }

    pub fn send_msg(&mut self, m: Msg) -> &mut Self {
        self.orders.push_back(Order::Message(m));
        self
    }

    pub fn perform_cmd<O: ToCmdOutput<Msg>>(
        &mut self,
        cmd: impl Future<Output = O> + 'static,
    ) -> &mut Self {
        let cmd = cmd.map(|o| <O as ToCmdOutput<Msg>>::to_cmd_output(o));

        self.orders.push_back(Order::Command(Box::pin(cmd)));
        self
    }

    pub fn execute<O: Orders<Msg>>(&mut self, orders: &mut O) -> &mut Self {
        if let Some(should_render) = self.should_render.take() {
            match should_render {
                ShouldRender::Render => {
                    orders.render();
                }
                ShouldRender::ForceRenderNow => {
                    orders.force_render_now();
                }
                ShouldRender::Skip => {
                    orders.skip();
                }
            }
        }

        for order in self.orders.drain(..) {
            match order {
                Order::Command(cmd) => {
                    orders.perform_cmd(cmd);
                }
                Order::Message(msg) => {
                    orders.send_msg(msg);
                }
                Order::Notification(msg) => orders.clone_app().notify_with_notification(msg),
            }
        }

        self
    }

    pub fn merge(&mut self, mut other: SimpleOrders<Msg>) -> &mut Self {
        self.orders.append(&mut other.orders);
        self.should_render = other.should_render.or(self.should_render.take());
        self
    }
}
```

(`ToCmdOutput<Msg>` is a trait built with OIBTs to avoid the whole runtime panics situation)

This is easily usable in a trait object as it's just a struct.
