### ISSUE TITLE
img! macro not working

### ISSUE THREAD

**Issue by frankli-dev** [seed-rs/seed#532]
Thanks to the great seed framework!

I think this is a simple issue but I can't find the reason why the img! macro not working
Here is my codebase

```
fn view(model: &Model) -> Node<Msg> {
    div![
        img![C!["logo"], attrs!{At::Src => "https://a.com/a.png"}],
        input![
            attrs! {
                At::Placeholder => "Enter your name..."
            },
            input_ev(Ev::Input, Msg::ChangeText),
        ],  
   ]
}
```

It shows an input but I can't see the logo. (https://a.com/a.png is just a temporary)
Also, if I check the dev tools, I can't find any img tag

Could anyone let me know what I mistake, please?
Thanks in advance.

**Comment by MartinKavik** [comment]
> oh. I think it was a cache issue
I've fixed by clearing the cache and rebuild my wasm

- `@frankli` on Seed chat

Solution: https://github.com/seed-rs/seed-rs.org/issues/71#issuecomment-687136462
