### ISSUE TITLE
Seed 0.8.0

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#551]
I want to release Seed 0.8.0, because:
- There are many improvements in the changelog and the latest Seed version is quite old.
- I think it will be the most stable and feature-complete version so far.
- Seed will be ready for next breaking changes / improvements. Possible options are:
  - [Better routing/url](https://github.com/seed-rs/seed/pull/536)
  - [Better and final element macros API](https://github.com/seed-rs/seed/issues/525)
  - [Better error handling](https://github.com/seed-rs/seed/issues/544)
  - [Trunk integration](https://github.com/thedodd/trunk)
  - [Styles and Hooks integration](https://github.com/seed-rs/styles_hooks)

Notes:
  - Related PR - https://github.com/seed-rs/seed/pull/550
  - https://seed-rs.org/ is updated and `0.8.0` is the default one already - we only have to change `Soon` to a real date once released. 

@David-OConnor : Could you release it? Everything should be ready.

---

# Release Checklist

This is a list of steps to complete when making a new release.

# Before the release

- [x] 1. Create a new issue in the Seed repo with the name `Seed x.x.x` and copy-paste this checklist into it (also add blockers and additional tasks, if exist).
- [x] 2. Update all official examples.
- [x] 3. Review the commit and PR history since last release. Ensure that all relevant
changes are included in `CHANGELOG.md`, and that breaking changes
are specifically annotated.
- [x] 4. Ensure the `README.md` reflects API changes.
- [x] 5. Update the `CHANGELOG.md` with the new release version.
- [x] 6. Ensure the version listed in `Cargo.toml` is updated.
- [x] 7. Update Rust tools: `rustup update`.
- [x] 8. Run `cargo make populate_all` to synchronize `St`, `At` and other enums with official values.
- [x] 9. Run `cargo make verify` to ensure tests pass, and `clippy` / `fmt` are run.
- [x] 10. Commit and push the repo.
- [x] 11. Check that CI pipeline passed.
- [x] 12. Run `cargo package`.
- [x] 13. Run `cargo publish`.
- [x] 14. Add a release on [Github](https://github.com/seed-rs/seed/releases), following the format of previous releases.
- [x] 15. Verify the [docs page](https://docs.rs/seed/) updated correctly.

# After the release

- [x] 16. Update all quickstarts.
- [x] 17. Write documentation for the current release on the website.
- [x] 18. Make sure the website's version selector shows the released version by default. 
- [x] 19. Notify authors of community tutorials, quickstarts and examples about a new Seed version.
- [x] 20. Write announcements (chat, forum, etc.).

**Comment by David-OConnor** [comment]
Done

**Comment by MartinKavik** [comment]
Thanks @David-OConnor!

Announcement: https://seed.discourse.group/t/seed-0-8-0-released/104 (+ the same on chat)

**Comment by svenstaro** [comment]
Can't this be closed?
