### ISSUE TITLE
Error in Documentation of fetch with post

### ISSUE THREAD

**Issue by Narfinger** [seed-rs/seed#552]
The documentation example is wrong as json returns a Result.
https://github.com/seed-rs/seed/blob/480141ce9e520c07e60ddae58244edb40c9f55e9/src/browser/fetch.rs#L64

**Comment by MartinKavik** [comment]
Perhaps we should split it and add `unwrap`:
```rust
/// let request = Request::new("/api").method(Method::Post).json(form).unwrap();
/// let response = fetch(request).await?;
``` 
Feel free to create a PR with changes, thank you!
