### ISSUE TITLE
How to style document element (<html>)?

### ISSUE THREAD

**Issue by mankinskin** [seed-rs/seed#574]
How would I about to change for example the `background-color` of the root element from seed?

**Comment by mankinskin** [comment]
So you can do it using web_sys directly
```rust
fn document_element() -> Option<Element> {
    window().document()?.document_element()
}
fn init_document() {
    let document = document_element().expect("Failed to get document element");
    let mut styles = document.get_attribute("style").unwrap_or("".into());
    document.set_attribute("style", &format!("{}{}: {};", styles,
            St::BackgroundColor, "#505050"));
}
```
but it is very verbose, error prone and hard to reuse.

Is there some way to just mount the seed app as the document? It would be nice if we could apply all of the code for seed nodes to the entire document node.

**Comment by mankinskin** [comment]
An improved version:
```rust
    let document = document_element().expect("Failed to get document element");
    let old_styles = document.get_attribute("style").unwrap_or("".into());
    let new_styles = vec![
        (St::BackgroundColor, "#bcb6b3"),
        (St::FontSize, "12pt")
    ].iter().fold(old_styles,
        |acc, (st, v)| format!("{}{}: {};", acc, st.as_str(), v));
    document.set_attribute("style", &new_styles)
        .expect("Failed to set document attribute");
```

**Comment by mankinskin** [comment]
This is the `index.html` that is served:
```html
<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
</head>
<section id="app"></section>
<script type="module">
    import init from '/package.js';
    init('/package_bg.wasm');
</script>
```

**Comment by MartinKavik** [comment]
I use the code like this:
```rust
GlobalStyle::new()
        .add_font_faces()
        .style(
            "html",
            s()
                .width(pc(100))
                .height(pc(100))
        )
        .style(
            "html",
            s()
                .only_and_below(Breakpoint::Small)
                .font_size(px(14))
        )
        .style(
            "body",
            s()
                .width(pc(100))
                .height(pc(100))
        )
        .style(
            "*",
            s()
                .list_style("none")
        )
        .style(
            "#app",
            s()
                .position(CssPosition::Relative)
                .z_index(CssZIndex::Integer(0))
                .width(pc(100))
                .height(pc(100))
        )
```
to setup global/root styles (with Seed Style help).

So yes, I would be glad if there would be a way to apply styles / nodes even to the HTML root. However we can't mount the app as a root document and we don't want to mount it directly to `body` because of conflicts with browser plugins and other things. That's why I'm not sure if there is a clear solution for the problem. Thoughts?

**Comment by mankinskin** [comment]
This seems fine if this can be applied to any element in the DOM, by some `GetElement` type. So we could do something like
`set_style(window().document()?, GlobalStyle::new()...)`. Or maybe even have trait methods implemented for `GetElement` types to do: `<window().document()? as Stylized>::set_style(GlobalStyle::new()...)`, with a `Stylized` trait.

**Comment by MartinKavik** [comment]
@mankinskin Feel free to design the API for it in https://github.com/seed-rs/seed/issues/525 or create an issue / PR in https://github.com/seed-rs/styles_hooks

**Comment by mankinskin** [comment]
Sure, I will look into it :+1:
