### ISSUE TITLE
Would it be possible to accept event handlers that do not implement `Clone`?

### ISSUE THREAD

**Issue by glennsl** [seed-rs/seed#584]
One use case for this is having a component with an unknown number of "actions", effectively a `Vec<Box<dyn FnOnce() -> Msg>>` or alternatively just `Vec<Msg>`.

Unfortunately, since `ev` requires the event handler implements `Clone`, the vec of closures is not possible because trait objects can not include non-auto-traits like `Clone`, i.e. `Vec<Box<dyn FnOnce() -> Msg + Clone>>` is not accepted by the compiler. And `Vec<Msg>` requires `Ms` to implement `Clone`, which is infectious and infeasible for all but the simplest of `Msg` types.

I have made some attempts to implement various alternative versions of `ev`, but have so far been unable to for various reasons related to moving and borrowing. I haven't even been able to make a simpler version without the macro and only accepting a handler that returns `Ms`. It seems to me that this should be doable though.

**Comment by MartinKavik** [comment]
Could you provide a simple example / use-case? I'm not sure I understand your motivation.

However I'm also not sure if it's possible - event handlers have to be callable multiple times - e.g. user clicks multiple times on a button. It means event handlers have to implement `Fn` ([related code](https://github.com/seed-rs/seed/blob/89245248e3d129967725361130437a5e0affef4b/src/virtual_dom/event_handler_manager/event_handler.rs#L8) in Seed). Function `ev` [accepts](https://github.com/seed-rs/seed/blob/28498c0f2dfd3f9a1d59535c385b856a62854805/src/browser/dom/event_handler.rs#L146) `FnOnce` + `Clone` because this combination can be "transformed" to `Fn`.

**Comment by glennsl** [comment]
I just discovered that the `component_builder` example does something similar to what I want, but with the requirement that `Msg` implements `Clone`. It uses `Vec<Rc<dyn Fn(MouseEvent) -> Ms>>`. So basically that, but without needing `Clone` on `Msg`.

Another use case is optional event handlers, where the type of the event handler would have to be explicitly annotated because of course it can't be inferred if it's not specified. A trait object or `Msg` value passed in directly would solve that as well I think.

The reason I'd like to avoid `Clone` on `Msg` is that it requires everything referenced by it to also implement `Clone`. Which isn't possible to derive for external types, for example.

I do see the problem with the closure needing to be callable multiple times, and realize that _something_ will have to be sacrificed. But would it not be possible to accept a `Fn` closure directly at least? That would of course be severely limited, but it should work for variants without a payload or with `Copy` payloads, which would cover quite a lot.

I also wonder if it would be possible to use a simple sub enum that implements `Clone`, and then map that into the actual `Msg` type after generating `Node<SimpleSubMsg>`. But that also seems like a whole bunch of indirection that shouldn't really be necessary.

Apologies for thinking out loud here. It's getting late and my mind is a mess at the moment. I'll do some more thinking and experimentation tomorrow to try to narrow it down a bit more.

**Comment by glennsl** [comment]
Ok, so it seems like `Clone` isn't actually needed on `Msg` in the `component_builder` example. Which means I can already use a `Fn` closure, as long as I wrap it in `Rc`.

> Function ev accepts FnOnce + Clone because this combination can be "transformed" to Fn.

I still haven't figured out how to do this. But if this is possible in general then I can have a builder function that takes a `FnOnce + Clone`, store it as a `Rc<Fn>` in the component and then create a `FnOnce` that calls that to pass to `ev` on render. That would solve everything I'm asking for here. Both a vec of closures without needing `Clone` on Msg` and optional event handlers without inference issues. In a not entirely obvious way, to be frank, but I'll take that!

Would you mind if I update the `component_builder` example to remove `Clone` on `Msg`, and perhaps add an optional left click event or something to illustrate that as well?

**Comment by flosse** [comment]
@glennsl Why do you need to embed fat data in `Msg`? I'd always keep the messages lightweight and store the data in the model.
Let's say you have s.th. like this:
```rust
#[derive(Debug, Clone)]
enum Msg {
   Big(Vec<Vec<(Foo, Bar)>>)
}
```
You could transform it to
```rust
type Id = u64;

#[derive(Debug, Clone, Copy)]
enum Msg {
   Small(Id, usize, usize)
}

struct Mdl {
  data:  HashMap<Id,Vec<Vec<(Foo, Bar)>>>
}

fn update(msg: Msg, mdl: &mut Mdl, _:&mut impl Orders<Msg>) {
    match msg {
        Msg::Small(id,i,j) => {
            if let Some(foo, bar) = mdl.data.get(id).and_then(|x|x.get(i)).and_then(|x|x.get(j)) {
                // process data
            }
        }
    }
}
```

**Comment by glennsl** [comment]
@flosse Well, to get that big chunk of data from the server in the first place you'll have to pass it through a `Msg`.

I think that's pretty much it though. For any other message I do as you suggest.

It would be cool if `Clone`/`Copy` could somehow be implemented for individual variants that don't have payloads or whose payloads themselves implement `Clone`/`Copy`...

**Comment by MartinKavik** [comment]
I agree with @flosse - `Msg` should be as small as possible. `Msg` with data from a fetch response may be more complex, but in most cases you just want to store it in your `Model` so there are no problems with event handlers or other APIs.  

Derive / manually implement `Clone` for `Msg` is an anti-pattern. That's why `ev` has replaced `simple_ev` - `simple_ev` has been deprecated because it requires `Msg: Clone`. And there was a big Seed refactor focused on removing `Msg: Clone` constraints.

> MartinKavik: "Function ev accepts FnOnce + Clone because this combination can be "transformed" to Fn."
> glennsl: "I still haven't figured out how to do this."

If function accepts `FnOnce + Clone`, then it automatically accepts also `Fn` and `fn` (`fn` is basically `Fn + Copy`). So no actions needed. 
However if you want to "transform" `FnOnce + Clone` to `Fn + Clone` by yourself, it looks like:
```rust
fn foo(my_fn_once: impl FnOnce(arg: i32) + Clone + 'static) {
    let my_fn = move |arg: i32| my_fn_once.clone()(arg);  
    my_fn(1);
    my_fn(2);
}
```

@glennsl Please provide a link / paste code with a simple example so we can talk about a clear use-case. I prefer to use "example-driven development". Thanks!

**Comment by glennsl** [comment]
> Derive / manually implement Clone for Msg is an anti-pattern. 

Good to hear! I've opened #586 to remove it from the `component_builder` example.

> However if you want to "transform" FnOnce + Clone to Fn + Clone by yourself, it looks like:

It really is that simple, huh. And I see the `component_builder` example does exactly this as well, but I guess I dismissed it or got confused by the `Clone` on `Msg` here too.

> Please provide a link / paste code with a simple example so we can talk about a clear use-case. I prefer to use "example-driven development". 

`component_builder` is pretty much exactly what I want, so I'd say this is resolved now. I was just a bit confused as I didn't understand that you could go from `FnOnce + Clone` to `Rc<Fn>`, then back to `FnOnce + Clone` again, without needing `Clone` on `Msg`.

So the direct answer to the question "Would it be possible to accept event handlers that do not implement `Clone`?" is: It already is possible, because you can wrap a `Fn` in `Rc` and call that from a `FnOnce + Clone`.

I'll do better at providing examples in future inquiries. Thanks for helping me understand!
