### ISSUE TITLE
Return multiple messages

### ISSUE THREAD

**Issue by fxdave** [seed-rs/seed#593]
Can I do something like this?

```rust

fn handle_mouse_up(e: &web_sys::MouseEvent) -> MsgGenerator {
    // ... do something with web_sys
    yield Msg::Something;
    // ... do something else with web_sys
    yield Msg::SomethingElse;
}

```
Or

```rust

fn handle_mouse_up(e: &web_sys::MouseEvent) -> Vec<dyn Fn() -> Msg> {
   vec![
       |_| {
            // actual render
            // ... do something with web_sys
            Msg::Something
       },
       |_| {
            // next render
            // ... do something else with web_sys
            Msg::SomethingElse
       }
   ]
}

```

I know rust's generator API is unstable. But is there a way to achieve this need?

**Comment by MartinKavik** [comment]
> For this I need to reset the dragging element's position first, which requires a rerender, then I need to check which element is on the actual mouse position.

It sounds a bit cumbersome - can you use something like https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event instead?

> Currently I'm using a workaround where I hide the element and unhide it after I get the element.

According to https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint, you can toggle `pointer-events` instead of visibility (it sounds less invasive imho)

**Comment by fxdave** [comment]
> It sounds a bit cumbersome - can you use something like https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event instead?

I want this for SVG, which does not support drag* events. 

> According to https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint, you can toggle pointer-events instead of visibility (it sounds less invasive imho)

Thanks for the advice.

**Comment by fxdave** [comment]
Closing this because this is more likely the SVG's fault.

**Comment by glennsl** [comment]
I'm still not sure how parallel message dispatching would help with here, as it still sounds like a sequence of messages should do the trick. But perhaps using [`Orders::after_next_render`](https://docs.rs/seed/0.8.0/seed/app/orders/trait.Orders.html#tymethod.after_next_render) would be helpful.

**Comment by fxdave** [comment]
I don't want to pollute update function with web_sys and view does not have `Orders`. But yes, `after_next_render` would solve the issue.

**Comment by glennsl** [comment]
Yeah, I can see that. Another option for dealing with messy DOM interaction is to create a web component. That carries a big overhead in itself, of course, but at least it's encapsulated and can expose a nice, clean and declarative API.
