### ISSUE TITLE
Intersection observer example

### ISSUE THREAD

**Issue by allan2** [seed-rs/seed#612]
I'd like to add an example for intersection observer. However, I haven't done it properly.

My repo is https://github.com/allan2/seed-intersection-observer

The observer is working but passing the value through `msg_sender` isn't working.
Any suggestions would be helpful.

**Comment by MartinKavik** [comment]
https://github.com/allan2/seed-intersection-observer/pull/1

**Comment by allan2** [comment]
PR #613 opened
