### ISSUE TITLE
Return error details in `FetchError`

### ISSUE THREAD

**Issue by aklajnert** [seed-rs/seed#616]
I was using the `fetch()` API as shown in the [example](https://github.com/seed-rs/seed/blob/480141ce9e520c07e60ddae58244edb40c9f55e9/examples/server_integration/client/src/example_a.rs), using `check_status()` helper function. Unfortunately, this function has a pretty significant flaw - it hides the error details returned from the backend.

Let's say, backend returns error `500` with following response:  
```json
{"details":"cannot connect to the database"}
```

If I'll `log!()` such error in Seed, I'll get this:  
```
StatusError(
    Status {
        code: 500,
        text: "Internal Server Error",
        category: ServerError,
    },
)
```

There's no way to figure out what happened in the server, as the `details` are now gone. It would be great to have `response` in `Status` that would contain the server response. 

For now, I'm not using `check_status()` and manually check for `status()` to return an error, but it feels a bit clunky. Is there any better way?

**Comment by MartinKavik** [comment]
Feel free to create a PR with basic implementation of suggested new API.
