### ISSUE TITLE
Serialize or/and Deserialize failing

### ISSUE THREAD

**Issue by arn-the-long-beard** [seed-rs/seed#619]
Hello guys :wink: ,

Well my main project is now failling its Apis calls that contains objects to post.

### Before Update 

![image](https://user-images.githubusercontent.com/30114057/132011910-44841613-0480-4c3e-9f3b-88dfa514b738.png)

1 - From the web browser

![image](https://user-images.githubusercontent.com/30114057/132011967-9566d796-c55a-4b26-836b-1d5008ed2a8d.png)

2 - From the web browser

### After Update

![image](https://user-images.githubusercontent.com/30114057/132012315-9b411d4c-5d81-4b4a-a30d-da7799a63cb5.png)

3 -From the web browser

![image](https://user-images.githubusercontent.com/30114057/132012349-7179a6fe-deb4-4a6c-9f0f-42b50a3c82d5.png)

4 - From the web browser

![image](https://user-images.githubusercontent.com/30114057/132012460-a95bf65c-4b3a-4acf-884a-ca2a5bde9059.png)

5 - From the terminal

Here is my code 

#### Send email to backend for checking

```rust
      let email_form = FormEmail::new(model.email.clone());

            let request = Request::new("/api/email")
                .method(Method::Post)
                .json(&email_form)
                .expect("Serialization failed");
                
                
         orders.perform_cmd(async {
                RequestState::send(request)
                    .await
                    .map_err(|e| e.message().to_string())
                    .map_or_else(Msg::ValidateEmailFailed, Msg::ValidateEmailSucceed)
            });          

```

#### RequestState is a wrapper for making request and getting error message from backend 

```rust 
impl<T: 'static + DeserializeOwned> RequestState<T> {
    /// Send the request with `fetch(request).await?;` and catch every possible
    /// `FetchError` to ClientError;
    #[allow(clippy::needless_lifetimes)]
    pub async fn send<'a>(request: Request<'a>) -> Result<T, ClientError> {
        let response = fetch(request).await?;
        let status = response.status();

        if status.is_error() {
            let text = response.text().await?;
            return Err(ClientError::new(&text, &status.code.to_string()));
        }
        Ok(response.json().await?)
    }

    pub fn is_loading(&self) -> bool {
        match self {
            RequestState::IsPending(is_loading) => *is_loading,
            _ => false,
        }
    }
}
```

#### The data Model 

```rust

use serde::{Deserialize, Serialize};
#[derive(Deserialize, Serialize)]
pub struct FormEmail {
    email: String,
}
```

I do not know what is happening there and why my object is not passed like before as json. 

Any clue or indication on what I could do to fix it ?

**Comment by arn-the-long-beard** [comment]
I guess on part of the problem is that I do not get my error from the server as before.
The second part and most important, my data models are not serialized as json anymore.

**Comment by glennsl** [comment]
Might be because of https://github.com/seed-rs/seed/pull/618#discussion_r697715878

**Comment by arn-the-long-beard** [comment]
Thank you for the link mate. Yes it seems related.

And yes @RReverser is right there.

**Comment by fosskers** [comment]
I'd call this a bug and not necessarily a breaking change. Let me see what I can do to fix it.

**Comment by linuxuser586** [comment]
What is the solution to this? I tried running the graphql example and it is fails because it serializes to object.

**Comment by fosskers** [comment]
Sigh, the solution is that I try harder to fix my fix. Sorry about the trouble.

**Comment by arn-the-long-beard** [comment]
Well I need we reopen the issue :D I am documenting why I am using patch  in my cargo to older version of Seed.

**Comment by flosse** [comment]
If someone can write a test that fails and reflect this bug I can try fix it :)

**Comment by fosskers** [comment]
It's an edge-case somewhere involving `String` serialization.

**Comment by flosse** [comment]
@arn-the-long-beard could you check if #659 resolves your problem?

**Comment by flosse** [comment]
I assume that the problem should be solved now.
