### ISSUE TITLE
Hash path is not updated on IOS

### ISSUE THREAD

**Issue by thestarmaker** [seed-rs/seed#625]
I've encountered some strange behaviour, wondering if this is a bug or something. The same happens in my app asn in ToDo example (https://seed-app-todomvc.netlify.app/).

Desktop browser (Firefox):
* open https://seed-app-todomvc.netlify.app/ 
* add todo
* click through filters
Expect: hash path in browser address bar changes accordingly (/#completed, /#active, etc).
Actual: as expected.

Mobile browser (also Firefox, on IOS):
* open https://seed-app-todomvc.netlify.app/ 
* add todo
* click through filters
Expect: hash path in browser address bar changes accordingly (/#completed, /#active, etc).
Actual: hash path does NOT change.

I have tried the same on Andoid Firefox, everything works fine. 

I've also found this old thread:
https://try2explore.com/questions/10442473

It seems that IOS does not like changing address bar on History.pushChange() but it seems from that forum thread that there are some libraries that do manage to somehow force the address bar update (namely history.js).

Clarification: please note that Firefox on IOS (same as all browsers on IOS) is WebKit-based! It is possible that the bug is WebKit related.

**Comment by thestarmaker** [comment]
Update: 

I have misunderstood symptoms that I saw, here is the true story

The behaviour is actually consistent between OSes:

if I navigate straight to https://seed-app-todomvc.netlify.app/#completed and then click "Active", then the url changes to #active. If I click "All", then url changes to the path that was used to load the app - "#completed" though I would expect it to go back to "/" in this case.  This is totaly application related, I recon this it's to do with  "All" being at / path.

Apologise!

**Comment by fosskers** [comment]
No problem! Thanks for taking to the time report.
