### ISSUE TITLE
checkbox not working

### ISSUE THREAD

**Issue by cheolgyu** [seed-rs/seed#705]
The checkbox does not work if the model value is entered in the at::checked property value of the checkbox's attr. 

How do I put the value of the model in the at::checked of the attr of the checkbox and make the checkbox work?

**Comment by flosse** [comment]
I guess you need to convert the value with [`AsAtValue::as_at_value`](https://docs.rs/seed/latest/seed/virtual_dom/values/trait.AsAtValue.html#tymethod.as_at_value) => `your_value.as_at_value()`.

**Comment by cheolgyu** [comment]
> [`AsAtValue::as_at_value`](https://docs.rs/seed/latest/seed/virtual_dom/values/trait.AsAtValue.html#tymethod.as_at_value)=> 로 값을 변환해야 할 것 같습니다 `your_value.as_at_value()`.

thank you. thank you
