### ISSUE TITLE
Session storage.

### ISSUE THREAD

**Issue by thedodd** [seed-rs/seed#87]
As far as I can tell, the current `seed::storage` module only exposes access to local storage.

Any reason session storage has not been exposed? Probably just a matter of it not having been implemented yet, but I figured I would just go ahead and pop an issue for it.

Happy to help code this up. Interface is pretty damn near identical.

**Comment by David-OConnor** [comment]
You're correct - this was something I neglected; meant to have a fleshed-out storage module.

**Comment by thedodd** [comment]
+1
